/* GENERATED by tooling/build-ui.mjs. Edit packages/workspace-ui or packages/contracts, not this file. */
export default [
  [
    "/refunds",
    [
      "index.html",
      "text/html; charset=utf-8"
    ]
  ],
  [
    "/",
    [
      "index.html",
      "text/html; charset=utf-8"
    ]
  ],
  [
    "/index.html",
    [
      "index.html",
      "text/html; charset=utf-8"
    ]
  ],
  [
    "/products",
    [
      "product-commands.html",
      "text/html; charset=utf-8"
    ]
  ],
  [
    "/product-commands.html",
    [
      "product-commands.html",
      "text/html; charset=utf-8"
    ]
  ],
  [
    "/logs",
    [
      "playfab-logs.html",
      "text/html; charset=utf-8"
    ]
  ],
  [
    "/playfab-logs.html",
    [
      "playfab-logs.html",
      "text/html; charset=utf-8"
    ]
  ],
  [
    "/players",
    [
      "player-data.html",
      "text/html; charset=utf-8"
    ]
  ],
  [
    "/player-data.html",
    [
      "player-data.html",
      "text/html; charset=utf-8"
    ]
  ]
];
