import React from 'react';
import type {Plan,Store} from '../shared/domain';

const names:Record<Store,string>={google:'Google Play',apple:'App Store',steam:'Steam'};
const actionLabel={skip:'기존 상품 보호',create:'신규 생성',update:'변경 예정'} as const;
export function PlanReviewPage({plan,busy,onBack,onExecute}:{plan:Plan;busy:boolean;onBack:()=>void;onExecute:()=>void}){
  const creates=plan.rows.filter(row=>row.action==='create').length,skips=plan.rows.filter(row=>row.action==='skip').length;
  return <section className="product-workspace"><div className="detail-heading"><div><button className="cw-button" data-variant="quiet" type="button" onClick={onBack}>← 상품 목록</button><div className="eyebrow">UPLOAD PLAN</div><h2>업로드 계획 검토</h2><p>{plan.game.name} · {plan.rows.length}개 플랫폼 작업 · 계획 ID <code>{plan.id}</code></p></div><span className="cw-state-pill" data-tone={skips?'warning':'success'}>신규 {creates} · 보호 {skips}</span></div>
    <section className="guard"><span className="shield">✓</span><div><strong>기존 모바일 상품 보호가 적용됩니다</strong><p>Google Play와 App Store에서 이미 존재하는 상품은 이름·가격·판매 상태를 포함해 변경하지 않습니다.</p></div></section>
    <section className="panel plan-page"><div className="panel-head"><div><h3>플랫폼별 예정 작업</h3><p>현재 스토어 값과 이번 작업에서 사용할 웹 설정을 확인하세요.</p></div></div>{plan.rows.map((row,index)=>{const missing=[!row.desired.product.description&&'기본 설명',!Object.keys(row.desired.product.localizations).length&&'번역',!row.desired.settings.countries.length&&'판매 지역',row.store==='apple'&&!row.desired.settings.reviewImageRef&&'심사 이미지',!row.desired.product.gameReady&&'게임 검증'].filter(Boolean) as string[];return <article className="plan-row" key={`${row.productKey}:${row.store}:${index}`}><div className="plan-title"><div><strong>{row.desired.product.name}</strong><small>{names[row.store]} · {row.remoteId}</small></div><span className={`badge ${row.action}`}>{actionLabel[row.action]}</span></div>{row.action==='skip'?<p className="safe-text">기존 상품입니다. 외부 변경 요청 없이 건너뜁니다.</p>:<><div className="plan-comparison"><div><span>현재 스토어</span><strong>{row.before?'등록값 있음':'등록되지 않음'}</strong></div><div><span>다음 등록값</span><strong>{Number(row.desired.preset.krw).toLocaleString('ko-KR')}원 · {row.desired.product.type==='consumable'?'소모성':'비소모성'}</strong><small>판매 지역 {row.desired.settings.countries.length}개 · 번역 {Object.keys(row.desired.product.localizations).length}개</small></div><div><span>예정 단계</span><strong>{row.steps.map(step=>step.key).join(', ')||'생성 확인'}</strong></div></div>{missing.length>0&&<p className="plan-missing" role="status">확인 필요: {missing.join(', ')}</p>}</>}</article>;})}</section>
    <div className="release-actions"><p>실행 후에는 업로드 이력에서 플랫폼별 결과와 재시도 상태를 확인할 수 있습니다.</p><button className="cw-button" data-variant="primary" type="button" disabled={busy||creates===0&&plan.rows.every(row=>row.action==='skip')} onClick={onExecute}>{busy?'작업 접수 중…':'이 계획 실행'}</button></div>
  </section>;
}
