import React,{useEffect,useState} from 'react';
import type {Product,Preset,StorePrice,StoreProductSnapshot} from '../shared/domain';
import {ApplePriceSelect,type PriceMatrixChoice} from './ApplePriceSelect';
const languages={'en-US':'영어 (미국)','ja-JP':'일본어','zh-Hans':'중국어 간체','zh-Hant':'중국어 번체','de-DE':'독일어','fr-FR':'프랑스어','es-ES':'스페인어','pt-BR':'포르투갈어 (브라질)','th':'태국어','vi':'베트남어'};
type SelectedPrice={matrixVersion:string;tierId:string};
export function ProductContentEditor({product,presets,storeDetails,section='all',onDirtyChange,onSave}:{product:Product;presets:Preset[];storeDetails:StoreProductSnapshot[];section?:'all'|'content'|'price';onDirtyChange?:(dirty:boolean)=>void;onSave:(content:unknown,price?:SelectedPrice)=>Promise<void>}){
  const currentPreset=presets.find(preset=>preset.key===product.pricePresetKey),currentPrice=currentPreset?.apple.KOR;
  const currentKrw=storeDetails.flatMap(detail=>detail.prices.map(price=>({store:detail.store,...price}))).sort((a,b)=>storePriority(a)-storePriority(b)).find(price=>price.currency==='KRW'&&['KR','KOR','KRW'].includes(price.market));
  const korean=product.localizations['ko-KR']??product.localizations.ko;
  const [name,setName]=useState(korean?.name??product.name),[description,setDescription]=useState(korean?.description??product.description??'');
  const [type,setType]=useState(product.type),[price,setPrice]=useState<PriceMatrixChoice>({pricePointId:currentPrice?.pricePointId??'',selectionId:currentPrice?.selectionId,amount:currentPreset?.krw??currentKrw?.amount??'',currency:'KRW'}),[selectedPrice,setSelectedPrice]=useState<SelectedPrice|undefined>(),[locales,setLocales]=useState(Object.fromEntries(Object.entries(product.localizations).filter(([key])=>key!=='ko-KR'&&key!=='ko'))),[locale,setLocale]=useState('en-US'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sourceNotice,setSourceNotice]=useState('');
  const baseline=JSON.stringify({name:korean?.name??product.name,description:korean?.description??product.description??'',type:product.type,locales:Object.fromEntries(Object.entries(product.localizations).filter(([key])=>key!=='ko-KR'&&key!=='ko')),pricePresetKey:product.pricePresetKey}),dirty=JSON.stringify({name,description,type,locales,pricePresetKey:selectedPrice?.tierId??product.pricePresetKey})!==baseline;
  useEffect(()=>{onDirtyChange?.(dirty);return()=>onDirtyChange?.(false);},[dirty,onDirtyChange]);
  async function save(){setBusy(true);setError('');try{await onSave({name,description,type,localizations:{...locales,'ko-KR':{name,description}}},selectedPrice);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function loadStoreContent(detail:StoreProductSnapshot){const normalized=Object.fromEntries(Object.entries(detail.localizations).map(([key,value])=>[key==='ko'?'ko-KR':key,value])),korean=normalized['ko-KR'];if(korean){setName(korean.name);setDescription(korean.description);}setLocales(Object.fromEntries(Object.entries(normalized).filter(([key])=>key!=='ko-KR')));if(type==='unconfigured'&&detail.type!=='unconfigured')setType(detail.type);setSourceNotice(`${storeName(detail.store)} 번역 ${Object.keys(detail.localizations).length}개를 편집기에 불러왔습니다. 상품 내용 저장을 눌러야 반영됩니다.`);}
  const translationSources=storeDetails.filter(detail=>Object.keys(detail.localizations).length>0);
  return <section className="content-editor"><p>시트 식별용 이름: {product.sourceName??product.name}. 이 설정은 웹에 보관하며 시트 재가져오기로 덮어쓰지 않습니다.</p>
    {section!=='price'&&<>{translationSources.length>0&&<section className="store-translation-sources"><h3>스토어 번역 가져오기</h3><p className="muted">스토어에서 읽은 이름·설명을 편집기에 채웁니다. 원격 스토어는 변경하지 않습니다.</p><div className="actions">{translationSources.map(detail=><button className="cw-button" type="button" key={detail.store} onClick={()=>loadStoreContent(detail)}>{storeName(detail.store)} 번역 {Object.keys(detail.localizations).length}개 불러오기</button>)}</div>{sourceNotice&&<p className="store-source-notice" role="status">{sourceNotice}</p>}</section>}
    {translationSources.length>0&&<section className="content-comparison" aria-label="상품 내용 비교"><div><span>웹 설정 · 다음 등록값</span><strong>{name}</strong><small>{description||'설명 없음'}</small></div>{translationSources.map(detail=>{const current=detail.localizations['ko-KR']??detail.localizations.ko;return <div key={detail.store}><span>현재 {storeName(detail.store)}</span><strong>{current?.name??detail.name}</strong><small>{(current?.description??detail.description)||'설명 없음'}</small></div>;})}</section>}
    <label>기본 상품명 (한국어)<input className="cw-form-control" value={name} onChange={e=>setName(e.target.value)}/></label>
    <label>기본 설명 (한국어)<textarea className="cw-form-control" value={description} onChange={e=>setDescription(e.target.value)}/></label>
    <label>상품 유형<select className="cw-form-control" value={type} disabled={product.type!=='unconfigured'} onChange={e=>setType(e.target.value as Product['type'])}><option value="unconfigured">유형 선택 필요</option><option value="consumable">소모성</option><option value="nonConsumable">비소모성</option></select></label>
    <h3>번역</h3>{Object.entries(locales).map(([key,value])=><div className="localization-editor" key={key}><strong>{languages[key as keyof typeof languages]??key} · {key}</strong><label>번역 이름<input className="cw-form-control" value={value.name} onChange={e=>setLocales({...locales,[key]:{...value,name:e.target.value}})}/></label><label>번역 설명<textarea className="cw-form-control" value={value.description} onChange={e=>setLocales({...locales,[key]:{...value,description:e.target.value}})}/></label><button className="cw-button" data-variant="danger" onClick={()=>{const copy={...locales};delete copy[key];setLocales(copy);}}>번역 제거</button></div>)}
    <div className="actions"><select className="cw-form-control" aria-label="추가할 번역 언어" value={locale} onChange={e=>setLocale(e.target.value)}>{Object.entries(languages).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button className="cw-button" disabled={!!locales[locale]} onClick={()=>setLocales({...locales,[locale]:{name:'',description:''}})}>번역 추가</button></div>
    </>}
    {section!=='content'&&<section className="product-price-picker"><h3>기본 가격</h3><p className="muted">전달된 CSV의 대한민국 판매가를 바로 선택하세요. 같은 행의 국가별 금액을 Google Play와 Steam에도 사용합니다.</p>{currentKrw&&<p className="store-price-source"><strong>{storeName(currentKrw.store)}에서 읽은 현재 한국 가격: {Number(currentKrw.amount).toLocaleString('ko-KR')} {currentKrw.currency}</strong>{!currentPreset&&<> · 같은 금액의 CSV 행을 자동 선택합니다.</>}</p>}<ApplePriceSelect value={price} onChange={choice=>{setPrice(choice);setSelectedPrice({matrixVersion:choice.selectionId!,tierId:choice.pricePointId});}}/>{storeDetails.length>0&&<details className="current-store-prices"><summary>스토어에서 읽은 가격 모두 보기</summary>{storeDetails.map(detail=><div key={detail.store}><strong>{storeName(detail.store)}</strong>{detail.prices.length?detail.prices.filter(value=>['KR','KOR','KRW'].includes(value.market)||value.currency==='KRW').map(value=><span key={`${value.market}:${value.currency}`}>{value.market} · {Number(value.amount).toLocaleString('ko-KR')} {value.currency}</span>):<span>가격을 아직 읽지 못했습니다.</span>}</div>)}</details>}</section>}
    {error&&<p className="price-error" role="alert">{error}</p>}<button className="cw-button primary" data-variant="primary" disabled={busy||(section!=='price'&&(!name.trim()||!description.trim()||type==='unconfigured'))||(section==='price'&&!currentPreset&&!selectedPrice)} onClick={save}>{section==='price'?'가격 저장':'상품 내용 저장'}</button><p>저장은 스토어 상품을 변경하지 않습니다. 기존 상품 ID와 확정한 유형은 유지합니다.</p>
  </section>;
}

function storeName(store:StoreProductSnapshot['store']){return store==='google'?'Google Play':store==='apple'?'App Store':'Steam';}
function storePriority(price:StorePrice&{store:StoreProductSnapshot['store']}){return price.store==='apple'?0:price.store==='google'?1:2;}
