import React,{useId,useMemo,useState} from 'react';
import type {PriceMarket} from '../shared/price-markets';

const normalize=(value:string)=>value.normalize('NFKC').toLocaleLowerCase('en').replace(/\s+/g,' ').trim();
export function SaleRegionPicker({store,value,markets,onChange}:{store:'google'|'apple';value:string[];markets:PriceMarket[];onChange:(next:string[])=>void}){
  const id=useId(),[query,setQuery]=useState(''),[selected,setSelected]=useState('');
  const marketMap=useMemo(()=>new Map(markets.map(market=>[market.code,market])),[markets]);
  const words=normalize(query).split(' ').filter(Boolean),results=markets.filter(market=>words.every(word=>market.search.includes(word))),chosen=results.find(market=>market.code===selected),canAdd=!!chosen&&!value.includes(chosen.code);
  return <section className="sale-region-picker" aria-labelledby={`${id}-title`}>
    <div className="sale-region-heading"><div><strong id={`${id}-title`}>App Store 상품 판매 지역</strong><p>Apple은 앱과 별도로 IAP 상품의 판매 지역을 요구합니다. 현재 선택은 {value.length}개 지역이며, 등록할 때만 적용됩니다.</p></div><div className="actions"><span className="badge">{value.length}개 선택</span><button className="cw-button" type="button" disabled={!markets.length||value.length===markets.length} onClick={()=>onChange(markets.map(market=>market.code))}>제공 지역 전체 선택</button></div></div>
    <div className="selected-regions" aria-label="선택된 판매 지역">{value.map(code=>{const market=marketMap.get(code),valid=!!market;return <div className={`selected-region ${valid?'':'invalid'}`} key={code}><span><strong>{market?.name??code}</strong><small>{code} · {market?.currency??'확인 필요'}{valid?'':' · 현재 Apple 목록에 없음'}</small></span><button className="cw-button" type="button" data-variant="quiet" disabled={value.length===1} aria-label={`${market?.name??code} 판매 지역 제거`} onClick={()=>onChange(value.filter(value=>value!==code))}>제거</button></div>;})}</div>
    <div className="market-picker compact-picker"><label htmlFor={`${id}-search`}>{store==='apple'?'App Store':'Google Play'} 국가 검색</label><input id={`${id}-search`} className="cw-form-control" type="search" placeholder="국가명 또는 코드 검색 (예: 일본, Japan, JP)" value={query} onChange={event=>{setQuery(event.target.value);setSelected('');}}/><label htmlFor={`${id}-results`}>검색 결과에서 국가 선택</label><select id={`${id}-results`} className="cw-form-control" size={Math.min(5,Math.max(2,results.length+1))} value={selected} onChange={event=>setSelected(event.target.value)}><option value="" disabled>{markets.length?results.length?'목록에서 선택해 주세요':'검색 결과가 없습니다':'판매 지역을 불러오지 못했습니다'}</option>{results.map(market=><option key={market.code} value={market.code} disabled={value.includes(market.code)}>{market.name} · {market.englishName} ({market.code}) · {market.currency}{value.includes(market.code)?' — 선택됨':''}</option>)}</select><div className="market-picker-footer"><p role="status">{chosen?`${chosen.name} · ${chosen.code} · ${chosen.currency}`:`${results.length}개 검색 결과`}</p><button className="cw-button" type="button" disabled={!canAdd} onClick={()=>{if(!chosen)return;onChange([...value,chosen.code]);setSelected('');setQuery('');}}>선택한 국가 추가</button></div></div>
  </section>;
}
