import React,{useEffect,useMemo,useState} from 'react';
import type {Preset,Product,Settings,Store} from '../shared/domain';
import {ApplePriceSelect,getJson,type AppleMatrixSummary,type PriceMatrixChoice} from './ApplePriceSelect';

const validAmount=(value:string)=>/^\d+(\.\d{1,6})?$/.test(value)&&Number(value)>0;
type Status={kind:'loading'|'success'|'error';title:string;message:string};
export function StorePriceOverrides({gameId,product,store,preset,settings,onChange,onStatus}:{gameId:string;product:Product;store:Store;preset?:Preset;settings:Settings;onChange:(settings:Settings)=>void;onStatus?:(status:Status)=>void}){
  const base=store==='google'?preset?.google:store==='steam'?preset?.steam:undefined;
  const codes=useMemo(()=>store==='google'?settings.countries.filter(code=>preset?.google[code]):store==='steam'?Object.keys(preset?.steam??{}):[],[store,settings.countries,preset]);
  const [selected,setSelected]=useState('KR'),[draft,setDraft]=useState('');
  const [appleSource,setAppleSource]=useState<AppleMatrixSummary>(),[appleBusy,setAppleBusy]=useState(false),[appleError,setAppleError]=useState('');
  const overrideSignature=JSON.stringify(settings.priceOverrides);
  useEffect(()=>{const next=codes.includes(selected)?selected:codes[0]??'';setSelected(next);const current=settings.priceOverrides[next],value=store==='google'?(preset?.google[next]?.amount??''):store==='steam'?(preset?.steam[next]??''):'';setDraft(current?.amount??value);},[store,preset?.key,codes.join(','),overrideSignature]);
  if(!preset)return <section className="store-price-overrides"><strong>스토어별 가격 예외</strong><p>먼저 상품의 CSV 기본 가격을 선택하세요.</p></section>;
  if(store==='apple'){
    const override=settings.priceOverrides.KOR,defaultPrice=preset.apple.KOR,value:PriceMatrixChoice={pricePointId:override?.referenceId??defaultPrice?.pricePointId??'',selectionId:override?.sourceVersion??defaultPrice?.selectionId,amount:override?.amount??defaultPrice?.amount??preset.krw,currency:'KRW'};
    async function loadApplePrices(){setAppleBusy(true);setAppleError('');onStatus?.({kind:'loading',title:'App Store 전체 가격 읽는 중',message:`${product.name}에 허용된 가격 포인트를 확인하고 있습니다.`});try{const list=await getJson(`/games/${gameId}/products/${product.productKey}/apple-price-points?refresh=true`);setAppleSource({id:list.id,sha256:list.id,sourceFile:'App Store Connect',territoryCount:1,currencyCount:1,sourceRowCount:list.points.length,points:list.points});onStatus?.({kind:'success',title:'App Store 전체 가격 읽기 완료',message:`검색 가능한 가격 ${list.points.length}개를 읽었습니다.`});}catch(error){const message=(error as Error).message;setAppleError(message);onStatus?.({kind:'error',title:'App Store 가격 조회 실패',message});}finally{setAppleBusy(false);}}
    return <details className="store-price-overrides"><summary>App Store 가격만 다르게 설정</summary><p>기본값은 상품에서 선택한 CSV 가격입니다. 계정에 승인된 확장 가격이 필요하면 App Store Connect에서 이 상품의 전체 가격을 읽으세요.</p><div className="actions"><button className="cw-button" type="button" disabled={appleBusy||!product.appleId} onClick={loadApplePrices}>{appleBusy?'App Store 가격 읽는 중…':'App Store 전체 가격 읽기 (확장 가격 포함)'}</button>{appleSource&&<button className="cw-button" type="button" onClick={()=>setAppleSource(undefined)}>CSV 가격만 보기</button>}</div>{appleError&&<p className="price-error" role="alert">{appleError}</p>}<ApplePriceSelect key={appleSource?.id??'csv'} source={appleSource} sourceLabel={appleSource?'App Store Connect 전체 가격':'제공 CSV'} value={value} onChange={choice=>onChange({...settings,priceOverrides:{KOR:{currency:'KRW',amount:choice.amount,referenceId:choice.pricePointId,sourceVersion:choice.selectionId}}})}/>{override&&<button className="cw-button" type="button" onClick={()=>onChange({...settings,priceOverrides:{}})}>CSV 기본 가격으로 되돌리기</button>}</details>;
  }
  const basePrice=store==='google'?(preset.google[selected]?{currency:preset.google[selected].currency,amount:preset.google[selected].amount}:undefined):(preset.steam[selected]?{currency:selected,amount:preset.steam[selected]}:undefined),override=settings.priceOverrides[selected];
  function save(){if(!selected||!basePrice||!validAmount(draft))return;const next={...settings.priceOverrides};if(Number(draft)===Number(basePrice.amount))delete next[selected];else next[selected]={currency:basePrice.currency,amount:draft};onChange({...settings,priceOverrides:next});}
  return <details className="store-price-overrides"><summary>{store==='google'?'Google Play 국가별':'Steam 통화별'} 가격만 다르게 설정</summary><p>선택한 CSV 행의 가격이 기본입니다. 이 상품에만 다른 금액이 필요할 때 예외를 저장하세요.</p><div className="price-override-row"><label>{store==='google'?'국가':'통화'}<select className="cw-form-control" value={selected} onChange={event=>{const code=event.target.value;setSelected(code);setDraft(settings.priceOverrides[code]?.amount??(store==='google'?preset.google[code]?.amount:preset.steam[code])??'');}}>{codes.map(code=><option key={code} value={code}>{code} · {store==='google'?preset.google[code]?.currency:code}</option>)}</select></label><label>판매 금액<input className="cw-form-control" inputMode="decimal" value={draft} aria-invalid={!!draft&&!validAmount(draft)} onChange={event=>setDraft(event.target.value)}/></label><button className="cw-button" type="button" disabled={!selected||!validAmount(draft)} onClick={save}>이 가격 사용</button></div>{basePrice&&<p>CSV 기본값: {Number(basePrice.amount).toLocaleString('ko-KR')} {basePrice.currency}{override&&<> · 현재 예외: {Number(override.amount).toLocaleString('ko-KR')} {override.currency}</>}</p>}{Object.keys(settings.priceOverrides).length>0&&<button className="cw-button" type="button" onClick={()=>onChange({...settings,priceOverrides:{}})}>이 스토어의 가격 예외 모두 제거</button>}</details>;
}
