import React from 'react';
import type {RemoteProductScan,Store} from '../shared/domain';

const names:Record<Store,string>={google:'Google Play',apple:'App Store',steam:'Steam'};
export function StoreImportPage({scan,busy,onBack,onScan,onLoadPrice,onLoadAllApplePrices,onImport}:{scan:RemoteProductScan|null;busy:boolean;onBack:()=>void;onScan:()=>void;onLoadPrice:(product:RemoteProductScan['products'][number])=>void;onLoadAllApplePrices:()=>void;onImport:()=>void}){
  return <section className="product-workspace"><div className="detail-heading"><div><button className="cw-button" data-variant="quiet" type="button" onClick={onBack}>← 상품 목록</button><div className="eyebrow">STORE IMPORT</div><h2>스토어에서 가져오기</h2><p>실제 스토어의 상품·번역·현재 가격을 읽어 웹 목록과 비교합니다. 원격 스토어에는 쓰지 않습니다.</p></div><button className="cw-button" data-variant="primary" type="button" disabled={busy} onClick={onScan}>{busy?'스토어 확인 중…':'스토어 다시 확인'}</button></div>
    {!scan?<section className="panel empty"><h3>스토어 상품 확인이 필요합니다</h3><p>연결된 Google Play·App Store·Steam 상품을 한 번에 조회합니다.</p><button className="cw-button" data-variant="primary" type="button" disabled={busy} onClick={onScan}>스토어 상품 확인</button></section>:
    <section className="panel remote-import-page" aria-label="스토어 상품 확인 결과"><div className="remote-import-heading"><div><h3>확인 결과</h3><p>{new Date(scan.scannedAt).toLocaleString('ko-KR')} 기준 · 플랫폼 값은 서로 덮어쓰지 않고 저장합니다.</p></div>{scan.products.some(product=>product.store==='apple'&&product.resourceId&&product.priceState==='separate_request')&&<button className="cw-button" disabled={busy} onClick={onLoadAllApplePrices}>App Store 현재 가격 전체 읽기</button>}</div><div className="remote-source-status">{(['google','apple','steam'] as Store[]).map(store=>{const source=scan.sources[store];return <span key={store} className={`cw-state-pill`} data-tone={source.state==='ok'?'success':source.state==='failed'?'danger':'warning'} title={source.message}>{names[store]} · {source.state==='ok'?`${source.count}개`:source.state==='cached'?`${source.count}개 캐시`:source.state==='not_connected'?'미연결':'조회 실패'}</span>;})}</div><div className="remote-source-messages">{(['google','apple','steam'] as Store[]).filter(store=>scan.sources[store].message).map(store=><p key={store} className={scan.sources[store].state==='failed'?'failed':'information'}><strong>{names[store]}</strong>{scan.sources[store].message}</p>)}</div>{scan.products.length?<div className="remote-product-list">{scan.products.map(product=>{const basePrice=product.prices.find(price=>price.market==='KR'||price.market==='KOR'||price.currency==='KRW')??product.prices[0];return <div className={`remote-product-row ${product.action==='conflict'?'disabled':''}`} key={product.id}><span className="remote-product-main"><strong>{product.name}</strong><small>{product.productKey} · {product.remoteId}</small><small>{Object.keys(product.localizations).length?`번역 ${Object.keys(product.localizations).length}개`:'번역 없음'}</small></span><span>{names[product.store]}</span><span className={`badge ${product.action==='conflict'?'failed':product.action==='refresh'?'done':'pending'}`}>{product.action==='new'?'새 웹 상품':product.action==='attach'?'스토어 ID 연결':product.action==='refresh'?'등록값 갱신':'ID 충돌'}</span><span className="remote-product-price">{basePrice?<><strong>{Number(basePrice.amount).toLocaleString('ko-KR')} {basePrice.currency}</strong><small>{basePrice.market} 기준 · {product.prices.length}개 지역/통화</small></>:<><strong>가격 미조회</strong><small>{product.priceMessage??'스토어 응답에 가격이 없습니다.'}</small>{product.priceState==='separate_request'&&product.resourceId&&<button className="cw-button" type="button" disabled={busy} onClick={()=>onLoadPrice(product)}>현재 가격 가져오기</button>}</>}</span>{product.message&&<small>{product.message}</small>}</div>;})}</div>:<p className="empty">조회된 스토어 상품이 없습니다.</p>}<div className="remote-import-footer"><p>충돌을 제외한 모든 플랫폼 정보를 웹에 저장합니다. 기존 웹 내용과 원격 스토어 값은 변경하지 않습니다.</p><button className="cw-button" data-variant="primary" disabled={busy||!scan.products.some(product=>product.action!=='conflict')} onClick={onImport}>연결 가능한 {scan.products.filter(product=>product.action!=='conflict').length}개 정보 저장</button></div></section>}
  </section>;
}
