import {useRef,useState,type FormEvent} from 'react';
import {confirmWorkspaceAction} from './generated/workspace-confirm';
import {WorkspaceState} from './generated/workspace-state';
import {ScheduleToastNotice} from './ScheduleToasts';
import {useWorkspaceModal} from './generated/workspace-modal';
import {ProjectIcon} from './ProjectIcon';
import {type Bootstrap,type WorkGoal} from './types';
import {usePlanningWrites} from './usePlanningWrites';

export function GoalsPanel({boot,close,changed}:{boot:Bootstrap;close:()=>void;changed:()=>Promise<void>}) {
  const dialog=useRef<HTMLDialogElement>(null);
  const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[projectId,setProjectId]=useState<number|null>(null),[showClosed,setShowClosed]=useState(false);
  const [editingId,setEditingId]=useState<number|null>(null),[editTitle,setEditTitle]=useState(''),[editDescription,setEditDescription]=useState(''),[editProjectId,setEditProjectId]=useState<number|null>(null);
  const writer=usePlanningWrites(boot,changed);useWorkspaceModal(dialog,{scope:'retain',canClose:()=>!writer.busy,onClose:close});
  function startEdit(goal:WorkGoal){writer.clear();setEditingId(goal.id);setEditTitle(goal.title);setEditDescription(goal.description);setEditProjectId(goal.projectId);}
  async function saveEdit(event:FormEvent,goal:WorkGoal){event.preventDefault();if(await writer.run('goal-update',`/api/work-goals/${goal.id}`,'PUT',{title:editTitle,description:editDescription,projectId:editProjectId,version:goal.version}))setEditingId(null);}
  async function toggle(goal:WorkGoal){const closing=!goal.closedAt,intent=await confirmWorkspaceAction({title:closing?'업무 목표를 종료할까요?':'업무 목표를 다시 열까요?',message:closing?'기존 업무의 연결은 유지되지만 새 업무에는 선택할 수 없습니다.':'새 업무에도 다시 연결할 수 있습니다.',confirmLabel:closing?'목표 종료':'목표 재개',details:[{label:'목표',value:goal.title}]});if(intent)await writer.run('goal-close',`/api/work-goals/${goal.id}/closed`,'PATCH',{closed:closing,version:goal.version});}
  const goals=(boot.goals||[]).filter(goal=>showClosed||!goal.closedAt);
  return <dialog className="cw-modal task-dialog goals-dialog" aria-label="업무 목표 관리" ref={dialog}><section className="detail-panel goals-panel"><button type="button" className="cw-button close" data-variant="quiet" aria-label="목표 관리 닫기" disabled={writer.busy} onClick={()=>dialog.current?.close()}>×</button><span className="eyebrow">WORK GOALS</span><h1>업무 목표 관리</h1><p className="muted">여러 부서의 업무를 하나의 목표로 묶습니다. 모든 직원이 목표를 만들고 종료할 수 있습니다. 연결된 업무는 일정의 목표별 보기에서 확인합니다.</p>
    <form className="goal-create" onSubmit={async event=>{event.preventDefault();if(await writer.run('goal-create','/api/work-goals','POST',{title,description,projectId,version:0})){setTitle('');setDescription('');setProjectId(null);}}}><label className="cw-form-field">목표 이름<input className="cw-form-control" required maxLength={200} value={title} onChange={event=>setTitle(event.target.value)} placeholder="예: 신규 캐릭터 슬라임 작업"/></label><label className="cw-form-field">연결 프로젝트<select className="cw-form-control" data-company-picker="project" value={projectId??''} onChange={event=>setProjectId(event.target.value?Number(event.target.value):null)}><option value="">전체 프로젝트 공통</option>{boot.projects.filter(project=>!project.archived).map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="cw-form-field">설명<textarea className="cw-form-control" rows={3} maxLength={2000} value={description} onChange={event=>setDescription(event.target.value)} placeholder="목표 범위와 완료 기준을 적어 주세요."/></label><button className="cw-button" data-variant="primary" disabled={writer.busy}>목표 등록</button></form>
    <label className="cw-check-control"><input className="cw-checkbox" type="checkbox" checked={showClosed} onChange={event=>setShowClosed(event.target.checked)}/> 종료된 목표 포함</label>
    <div className="goal-list">{goals.map(goal=>{const project=boot.projects.find(value=>value.id===goal.projectId),editing=editingId===goal.id;return <article key={goal.id} data-goal-id={goal.id} className={goal.closedAt?'closed':''}><header><span><ProjectIcon id={project?.id}/>{project?.name||'전체 프로젝트'}</span><span className="cw-state-pill" data-tone={goal.closedAt?'neutral':'success'}>{goal.closedAt?'종료':'진행 중'}</span></header>{editing?<form className="goal-edit" onSubmit={event=>void saveEdit(event,goal)}><label className="cw-form-field">목표 이름<input className="cw-form-control" required maxLength={200} value={editTitle} onChange={event=>setEditTitle(event.target.value)}/></label><label className="cw-form-field">연결 프로젝트<select className="cw-form-control" data-company-picker="project" value={editProjectId??''} onChange={event=>setEditProjectId(event.target.value?Number(event.target.value):null)}><option value="">전체 프로젝트 공통</option>{boot.projects.filter(value=>!value.archived||value.id===goal.projectId).map(value=><option key={value.id} value={value.id}>{value.name}{value.archived?' · 종료':''}</option>)}</select></label><label className="cw-form-field">설명<textarea className="cw-form-control" rows={3} maxLength={2000} value={editDescription} onChange={event=>setEditDescription(event.target.value)}/></label><div className="goal-card-actions"><button type="button" className="cw-button" data-size="compact" disabled={writer.busy} onClick={()=>setEditingId(null)}>취소</button><button type="submit" className="cw-button" data-size="compact" data-variant="primary" disabled={writer.busy}>저장</button></div></form>:<><h2>{goal.title}</h2>{goal.description&&<p>{goal.description}</p>}<div className="goal-card-actions"><button type="button" className="cw-button" data-size="compact" disabled={writer.busy||editingId!==null} onClick={()=>startEdit(goal)}>수정</button><button type="button" className="cw-button" data-size="compact" disabled={writer.busy||editingId!==null} onClick={()=>void toggle(goal)}>{goal.closedAt?'다시 열기':'종료'}</button></div></>}</article>})}</div>{!goals.length&&<WorkspaceState kind="empty" title="표시할 업무 목표가 없습니다."/>}
    <ScheduleToastNotice id="goal-write" state={writer.outcome}/></section></dialog>;
}
