export type Employee = { id: number; name: string; department: string; departmentId: number | null; projectIds: number[]; role: string; active: boolean; shared: boolean; isPrivate?: boolean; access: boolean; isAdmin: boolean };
export type Project = { id: number; name: string; color: string; isPrivate?: boolean; archived: boolean; version: number };
export type Lead = { id: number; employeeId: number; department: string; departmentId: number | null };
export type Status = 'planned' | 'progress' | 'done';
export type Task = { id: number; title: string; body: string; assigneeId: number; createdBy: number; projectId: number | null; goalId?: number | null; startDate: string | null; endDate: string | null; status: Status; archived: boolean; version: number; createdAt: string; updatedAt: string; scheduleItems?: TaskScheduleItem[]; sharedTodos?: SharedTaskTodo[] };
export type WorkGoal = { id:number; title:string; description:string; projectId:number|null; createdBy:number; closedAt:string|null; closedBy:number|null; version:number; createdAt:string; updatedAt:string };
export type TaskScheduleItem = { id:number; taskId:number; title:string; date:string; endDate?:string; createdBy:number; version:number; createdAt:string; updatedAt:string };
export type SharedTaskTodo = { id:number; taskId:number; title:string; createdBy:number; completedBy:number|null; completedAt:string|null; version:number; createdAt:string; updatedAt:string };
export type Attachment = { id: string; taskId: number | null; commentId: number | null; feedbackId?: number | null; feedbackCommentId?: number | null; name: string; contentType: string; size: number; ownerId?:number; createdAt?:string };
export type Comment = { id: number; taskId: number; authorId: number; parentId: number | null; body: string; deleted: boolean; version: number; createdAt: string; editedAt: string | null };
export type Change = { id: number; actorId: number; action: string; details: string; createdAt: string };
export type Detail = { task: Task; canEdit: boolean; comments: Comment[]; attachments: Attachment[]; history: Change[];
  scheduleItems?:TaskScheduleItem[]; sharedTodos?:SharedTaskTodo[];
  editing?:{actorId:string;stateToken:string};
  commentEditing?:{actorId:string;createStateToken:string;comments:{id:number;stateToken:string}[]} };
export type Bootstrap = { me: Employee; demo: boolean; csrfToken: string; employees: Employee[]; departments: { id: number; name: string; archived: boolean; handlesScheduleFeedback?: boolean }[]; leads: Lead[]; projects: Project[]; goals?:WorkGoal[] };
export type TaskList = { items: Task[]; total: number; editableIds: number[]; commentCounts: { taskId: number; count: number }[]; attachmentCounts: { taskId: number; count: number }[]; scheduleItems?:TaskScheduleItem[]; sharedTodos?:SharedTaskTodo[] };
export type FeedbackType='bug'|'improvement'|'question'|'other';
export type FeedbackPriority='low'|'normal'|'high'|'urgent';
export type FeedbackStatus='new'|'review'|'progress'|'resolved'|'rejected';
export type FeedbackItem={id:number;projectId:number;reporterId:number;assigneeId:number|null;linkedTaskId:number|null;type:FeedbackType;priority:FeedbackPriority;status:FeedbackStatus;title:string;body:string;resolution:string;version:number;createdAt:string;updatedAt:string};
export type FeedbackComment={id:number;feedbackId:number;authorId:number;parentId:number|null;body:string;deleted:boolean;version:number;createdAt:string;editedAt:string|null};
export type FeedbackRevision={id:number;feedbackId:number;actorId:number;action:string;beforeSnapshot:string;afterSnapshot:string;createdAt:string};
export type FeedbackList={items:FeedbackItem[];total:number;skip:number;take:number;commentCounts:{feedbackId:number;count:number}[];attachmentCounts:{feedbackId:number;count:number}[];canHandle:boolean};
export type FeedbackDetail={item:FeedbackItem;comments:FeedbackComment[];attachments:Attachment[];history:FeedbackRevision[];linkedTask:{id:number;title:string;status:Status;assigneeId:number;startDate:string|null;endDate:string|null;archived:boolean}|null;canEdit:boolean;canHandle:boolean;handlerIds:number[]};
export const milestoneTypes = { general: "일반", review: "검수", update: "업데이트", prototype: "프로토타입" } as const;
export type MilestoneType = keyof typeof milestoneTypes;
export type MilestoneSchedule = { type: MilestoneType; date: string; endDate?: string | null; memo?: string };
export type Milestone = { type?: MilestoneType; id: number; title: string; description: string; deadlineMemo?: string; date: string; endDate?: string | null; additionalSchedules?: MilestoneSchedule[]; projectId: number | null; version: number; createdBy?: number | null; updatedBy?: number | null; createdAt?: string | null; updatedAt?: string | null };
export type MilestoneAuditSnapshot = { type: MilestoneType; title: string; description: string; deadlineMemo?: string; date: string; endDate?: string | null; additionalSchedules: MilestoneSchedule[]; projectId: number | null };
export type MilestoneRevision = { id: number; milestoneId: number; actorId: number; action: 'create'|'update'|'delete'; beforeSnapshot: string; afterSnapshot: string; createdAt: string };
export type MilestoneEditing = { actorId: string; createStateToken: string; milestones: { id: number; stateToken: string }[] };
export type MilestonePage = { items: Milestone[]; editing: MilestoneEditing };
export type Notice = { id: number; taskId: number; commentId: number | null; message: string; isRead: boolean; createdAt: string };
export type PersonalTodo = { id: number; ownerId: number; title: string; sortOrder: number; completedAt: string | null; version: number; createdAt: string; updatedAt: string };
export type CalendarHoliday = { date: string; name: string };
export type Absences = { items: { employeeId: number; date: string; portion: string }[]; holidays?: CalendarHoliday[]; holidaysAvailable?: boolean; available: boolean; updatedAt: string | null };
export const statuses: Record<Status, string> = { planned: '예정', progress: '진행', done: '완료' };

export type ReleaseStatus = 'stable' | 'unstable' | 'rolled_back' | 'skipped' | 'unrecorded';
export type LegacyReleaseRecord = { id: number; projectId: number; releasedOn: string | null; notes: string; issue: string; sourceReference: string };
export type ReleaseRecord = { releasedOnUnknown?: boolean; sourceReference?: string; id: number; projectId: number; baseVersion: number; minor: number; releasedOn: string; notes: string; status: ReleaseStatus; issue: string; rollbackTargetId: number | null; resolvedInId: number | null; createdBy: number; version: number; updatedAt: string };
export type ReleaseRevision = { id: number; releaseId: number; actorId: number; snapshot: string; createdAt: string };
export const releaseStatuses: Record<ReleaseStatus, string> = { unrecorded: '상태 미기재', stable: '안정', unstable: '불안정', rolled_back: '롤백', skipped: '버전 건너뜀' };
export const releaseName = (r: Pick<ReleaseRecord, 'baseVersion' | 'minor'>) => r.minor ? `${r.baseVersion}.${r.minor}` : String(r.baseVersion);
