import {useEffect,useRef,useState} from 'react';
import {ApiError} from './api';
import {confirmWorkspaceAction} from './generated/workspace-confirm';
import {workspaceDocumentFormSession,createWorkspaceWriteTransport,type FormLease,type WorkspaceFormSession,type WorkspaceWriteTransport} from './generated/workspace-form';
import {createWorkspaceReadSession,type WorkspaceReadSession} from './generated/workspace-read';
import type {WorkspaceStateProps} from './generated/workspace-state';
import {captureMilestoneWrite,confirmMilestoneReceipt,milestoneActorScope,milestoneBody,milestoneWriteBaseline,type MilestoneDraft,type MilestoneReceipt,type MilestoneWrite,type MilestoneWriteKind} from './milestoneWrites';
import type {Bootstrap,Milestone,MilestonePage} from './types';

type Options={boot:Bootstrap;draft:MilestoneDraft;baseline?:Milestone;page?:MilestonePage;dirty:boolean;blocked:()=>boolean;refreshIdentity:()=>Promise<Bootstrap>;readPage:(signal?:AbortSignal)=>Promise<MilestonePage>;committed:(receipt:MilestoneReceipt)=>void;refreshed:(page:MilestonePage,receipt:MilestoneReceipt)=>void;conflicted:(page:MilestonePage)=>void};
type Operation={write:MilestoneWrite;lease:FormLease;current:()=>boolean;receipt?:MilestoneReceipt};let sequence=0;
export function useMilestoneWrites(options:Options){
  const live=useRef(options);live.current=options;const owner=useRef(`schedule-milestone-${++sequence}`),actor=useRef(milestoneActorScope(options.boot));
  const mounted=useRef(false),forms=useRef<WorkspaceFormSession|undefined>(undefined),transport=useRef<WorkspaceWriteTransport|undefined>(undefined),reads=useRef<WorkspaceReadSession|undefined>(undefined),operation=useRef<Operation|null>(null);
  const [busy,setBusy]=useState(false),[locked,setLocked]=useState(false),[outcome,setOutcome]=useState<WorkspaceStateProps|null>(null);
  const sameOwner=()=>mounted.current&&milestoneActorScope(live.current.boot)===actor.current&&!forms.current?.invalid;
  useEffect(()=>{mounted.current=true;let untrack:(()=>void)|undefined,unsubscribe:(()=>void)|undefined;try{forms.current=workspaceDocumentFormSession('schedule-milestone-writes');untrack=forms.current.track(owner.current,()=>live.current.dirty);const sync=()=>mounted.current&&setLocked(forms.current!.invalid);unsubscribe=forms.current.subscribe(sync);sync();reads.current=createWorkspaceReadSession();transport.current=createWorkspaceWriteTransport({isConnected:()=>mounted.current,onState:setOutcome,onSaved:(value,sent,context)=>{const active=operation.current;if(!active?.current()||!context.isCurrent())throw Error('주요 일정 저장 중 대상·계정 또는 초안이 변경되었습니다.');active.receipt=confirmMilestoneReceipt(value,active.write,sent);}});}catch(error){setLocked(true);setOutcome({kind:'error',message:(error as Error).message});}return()=>{mounted.current=false;operation.current?.lease.finish('unknown');transport.current?.dispose();reads.current?.dispose();untrack?.();unsubscribe?.();};},[]);
  useEffect(()=>{if(milestoneActorScope(options.boot)!==actor.current)forms.current?.invalidate();},[options.boot]);
  async function run(kind:MilestoneWriteKind){
    const start=live.current,page=start.page,session=forms.current,writer=transport.current,reader=reads.current;if(!page||!session||!writer||!reader||operation.current||start.blocked()||!sameOwner())return;
    let write:MilestoneWrite;try{write=captureMilestoneWrite(kind,start.draft,start.baseline,start.boot,page);}catch(error){setOutcome({kind:'error',title:'주요 일정 요청을 보내지 않았습니다.',message:(error as Error).message});return;}
    const lease=session.begin(owner.current,[`milestone:${write.targetId??'new'}:${write.stateToken}`]);if(!lease){setOutcome({kind:'error',title:'이전 주요 일정 기준으로 다시 저장할 수 없습니다.',message:'이미 처리했거나 변경된 기준입니다. 목록을 다시 열어 주세요.'});return;}
    const signature=JSON.stringify(milestoneBody(write.draft));const current=()=>{try{return sameOwner()&&lease.current&&!live.current.blocked()&&JSON.stringify(milestoneBody(live.current.draft))===signature&&live.current.baseline?.id===start.baseline?.id;}catch{return false;}};
    const active:Operation={write,lease,current},restoreFocus=document.activeElement instanceof HTMLElement?document.activeElement:undefined;operation.current=active;setBusy(true);setOutcome({kind:'loading',title:'주요 일정 대상과 계정을 확인합니다.'});let attempted=false,finished=false;
    try{const fresh=await reader.run('preflight',async signal=>{const directory=await start.refreshIdentity();signal.throwIfAborted();const next=await start.readPage(signal);signal.throwIfAborted();return{directory,page:next};});if(fresh.status==='cancelled'||!current())throw Error('확인 중 계정·대상 또는 초안이 변경되었습니다.');if(!fresh.isCurrent())throw Error('현재 주요 일정 저장 확인이 아닙니다.');if(fresh.status==='error')throw fresh.error;if(milestoneActorScope(fresh.value.directory)!==write.actorScope||milestoneWriteBaseline(fresh.value.page,write.actorId,write.targetId)!==write.stateToken)throw Error('주요 일정 또는 권한이 변경됐습니다. 최신 목록을 확인해 주세요.');
      const validate=()=>{try{return current()&&milestoneWriteBaseline(live.current.page!,write.actorId,write.targetId)===write.stateToken?null:'대상·계정 또는 초안이 변경되었습니다. 취소 후 다시 확인해 주세요.';}catch{return'현재 주요 일정 저장 기준을 확인할 수 없습니다.';}};setOutcome(null);
      const project=fresh.value.directory.projects.find(x=>x.id===write.draft.projectId);const intent=await confirmWorkspaceAction({title:kind==='delete'?'주요 일정을 삭제할까요?':kind==='update'?'주요 일정 변경을 저장할까요?':'주요 일정을 등록할까요?',message:kind==='delete'?'선택한 주요 일정을 영구 삭제합니다.':'확인한 내용으로 주요 일정을 저장합니다. 결과 확인 전에는 초안을 지우지 않습니다.',confirmLabel:kind==='delete'?'삭제':'저장',tone:kind==='delete'?'danger':undefined,returnFocus:restoreFocus,signal:lease.signal,validate,details:[{label:'주요 일정',value:write.draft.title},{label:'프로젝트',value:project?.name||'프로젝트 미지정',entity:{kind:'project',id:project?String(project.id):null,name:project?.name||'프로젝트 미지정'}},{label:'날짜',value:write.draft.date}]});if(!intent)return;const invalid=validate();if(invalid)throw Error(invalid);attempted=true;if(!lease.markSent())throw Error('저장 계정 범위가 변경되었습니다.');
      const result=await writer.send({url:write.targetId?`/api/milestones/${write.targetId}`:'/api/milestones',method:kind==='delete'?'DELETE':kind==='update'?'PUT':'POST',json:write.body,signal:lease.signal,headers:{'X-CSRF-TOKEN':fresh.value.directory.csrfToken,'X-Workspace-Actor':write.actorId,'X-Workspace-Milestone-State':write.stateToken}});const receipt=active.receipt;
      if(result.saved&&receipt&&current()){finished=true;lease.finish('saved');start.committed(receipt);setOutcome({kind:'success',title:kind==='delete'?'주요 일정을 삭제했습니다.':'주요 일정을 저장했습니다.'});try{const next=await start.readPage();if(sameOwner())start.refreshed(next,receipt);}catch{if(mounted.current)setOutcome({kind:'success',title:'저장은 완료했지만 목록 확인에 실패했습니다.',message:'다시 저장하지 말고 주요 일정 목록만 새로고침해 주세요.'});}}else{finished=true;lease.finish(result.outcome==='invalid'?'invalid':result.outcome==='conflict'?'conflict':result.outcome==='not-sent'?'cancelled':'unknown');if(result.outcome==='conflict')try{const next=await start.readPage();if(sameOwner())start.conflicted(next);}catch{/* The transport already presents the conflict; preserve the draft. */}}
    }catch(error){if(error instanceof ApiError&&[401,403].includes(error.status))document.dispatchEvent(new Event('workspace-entity-scope-change'));if(sameOwner())setOutcome({kind:'error',title:attempted?'주요 일정 저장 결과를 확인해 주세요.':'주요 일정 요청을 보내지 않았습니다.',message:(error as Error).message+' 작성 내용은 유지됩니다.'});}
    finally{if(!finished)lease.finish(attempted?'unknown':'cancelled');if(operation.current===active)operation.current=null;if(mounted.current){setBusy(false);if(restoreFocus)requestAnimationFrame(()=>{if(restoreFocus?.isConnected&&!restoreFocus.matches(':disabled'))restoreFocus.focus();});}}
  }
  const visible=locked&&(!outcome||outcome.kind==='loading'||outcome.kind==='success')?{kind:'denied' as const,title:'주요 일정 저장이 잠겼습니다.',message:'계정 변경 또는 미확정 요청이 있습니다. 내용을 보관하고 페이지를 다시 열어 주세요.'}:outcome;return{run,busy,locked,outcome:visible};
}
