import {test,expect} from '@playwright/test';
import {assertLeaveControls} from './support/leave-controls.mjs';
import {readFileSync,existsSync} from 'node:fs';
import {resolve,extname,sep} from 'node:path';
import {root} from '../build-ui.mjs';
const dir=resolve(root,'artifacts/razor'),media='application/vnd.company.workspace-form+json',state='[data-leave-self-state]',pending='9007199254740993',approved='9007199254740995',cancel='9007199254740997';
const row=id=>`#leaveRequestsArea [data-leave-self-action]:has(input[name=id][value="${id}"])`;
async function fixture(page,options={}) {
  const model=JSON.parse(readFileSync(resolve(dir,'leave.self-actions.json'),'utf8')),html=readFileSync(resolve(dir,'leave.self-actions.html'),'utf8');const writes=[],errors=[];let reads=0,release;
  page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/*',async route=>{
    const request=route.request(),url=new URL(request.url()),path=url.pathname;
    if(request.method()==='POST'){
      const sent=await new Request(request.url(),{method:'POST',headers:request.headers(),body:request.postDataBuffer()}).formData();const operation=url.searchParams.get('handler');writes.push({sent,operation});
      const query=new URLSearchParams();for(const key of ['Year','Month','CalendarView','SelfOnly','ShowOthers','ViewEmployeeId','RequestLimit','RequestPage'])if(sent.get(key))query.set(key,sent.get(key));
      const prior=sent.get('expectedStatus'),data={operation,employeeId:sent.get('expectedEmployeeId'),id:sent.get('id'),previousSnapshot:sent.get('expectedSnapshot'),previousStatus:prior,status:operation==='WithdrawCancel'?'Approved':prior==='Pending'?'Cancelled':'CancelRequested',navigateTo:'/Leave/Index?'+query};
      if(options.bad)data[options.bad]='wrong';if(options.hold)await new Promise(resolve=>{release=resolve;});
      return route.fulfill({status:options.status||200,contentType:media,json:options.status?{protocol:'workspace-form-v1',outcome:options.status===422?'invalid':options.status===409?'conflict':'unknown',message:'격리 오류'}:{protocol:'workspace-form-v1',outcome:'saved',message:'처리 완료',data}}).catch(()=>{});
    }
    if(path==='/api/workspace/context')return route.fulfill({json:model.context});
    if(path==='/api/workspace/navigation')return route.fulfill({json:model.navigation});
    if(path==='/api/workspace/notifications')return route.fulfill({json:{items:[],sources:[],unreadCount:0}});
    if(['/Leave','/Leave/Index'].includes(path)){reads++;return route.fulfill({body:html,contentType:'text/html'});}
    const base=resolve(root,'apps',url.hostname==='company.example.com'?'portal':'leave','wwwroot'),file=resolve(base,path.slice(1));
    if(file.startsWith(base+sep)&&existsSync(file)&&['.js','.css','.svg'].includes(extname(file)))return route.fulfill({body:readFileSync(file),contentType:{'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'}[extname(file)]});return route.abort();
  });
  await page.goto('https://leave.workspace.test/Leave');await page.waitForFunction(()=>window.CompanyForm&&document.querySelector('.cw-header'));return {model,writes,errors,reads:()=>reads,release:()=>release?.()};
}
async function send(page,id){await page.locator(row(id)+' button').click();await expect(page.getByRole('dialog',{name:/할까요/})).toBeVisible();await page.getByRole('dialog',{name:/할까요/}).locator('button').last().click();}
for(const width of [320,1440])for(const theme of ['light','dark'])test(`self cancel shared confirmation preserves application draft ${width} ${theme}`,async({page},info)=>{
  await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:theme});const f=await fixture(page,{hold:true});const complete=page.locator('.request-complete-label'),pillPalette=await page.evaluate(()=>{const p=document.createElement('span');document.body.append(p);p.style.cssText='color:var(--cw-muted);background:var(--cw-raised)';const s=getComputedStyle(p),result={color:s.color,background:s.backgroundColor};p.remove();return result;});await expect(complete).toHaveClass(/\bcw-state-pill\b/);await expect(complete).toHaveAttribute('data-tone','neutral');await expect(complete).toHaveCSS('color',pillPalette.color);await expect(complete).toHaveCSS('background-color',pillPalette.background);await complete.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('completed-pill.png'),animations:'disabled'});await page.locator('#openApplyPanel').click();await page.locator('[name="Input.WorkPlan"]').fill('다른 신청 초안');const button=page.locator(row(pending)+' button');
  await assertLeaveControls(page.locator('#leaveRequestsArea'));await assertLeaveControls(page.locator('#calendarMoveForm'));await button.hover();await assertLeaveControls(page.locator(row(pending)),{fields:false});
  await button.click();await expect(page.getByRole('dialog',{name:/할까요/})).toContainText('승인 대기 중인 신청');await expect(page.getByRole('dialog',{name:/할까요/})).toContainText(f.model.start);await expect(page.getByRole('dialog',{name:/할까요/})).toContainText('검증 사유');await page.screenshot({path:info.outputPath('self-confirm.png'),animations:'disabled'});await page.keyboard.press('Escape');await expect(button).toBeFocused();expect(f.writes).toHaveLength(0);
  await send(page,pending);await expect.poll(()=>f.writes.length).toBe(1);await page.locator(row(approved)).evaluate(form=>form.requestSubmit());expect(f.writes).toHaveLength(1);f.release();await expect(page.locator(state)).toContainText('처리 결과를 확인했습니다.');await expect(page.locator('[name="Input.WorkPlan"]')).toHaveValue('다른 신청 초안');await expect(button).toBeDisabled();expect(f.reads()).toBe(1);expect(f.writes[0].sent.get('id')).toBe(pending);expect(f.writes[0].sent.get('__RequestVerificationToken')).toBeTruthy();expect(f.writes[0].sent.get('expectedSnapshot')).toMatch(/^[a-f0-9]{64}$/);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);expect(f.errors).toEqual([]);
});
for(const id of [pending,approved,cancel])test(`self action exact transition reloads only after receipt ${id}`,async({page})=>{const f=await fixture(page);await send(page,id);await expect(page).toHaveURL(/\/Leave\/Index\?/);await page.waitForLoadState('domcontentloaded');expect(f.reads()).toBe(2);expect(f.writes).toHaveLength(1);expect(f.writes[0].operation).toBe(id===cancel?'WithdrawCancel':'Cancel');expect(f.errors).toEqual([]);});
for(const id of [pending,approved,cancel])test(`calendar detail uses identical self action ${id}`,async({page})=>{
  const f=await fixture(page);await page.locator(`#leaveCalendar td[data-date="${f.model.start}"]`).click();const trigger=page.locator(`.detail-cancel-button[data-request-id="${id}"]`);await expect(trigger).toBeVisible();await trigger.click();await expect(page.getByRole('dialog',{name:/할까요/})).toBeVisible();await page.keyboard.press('Escape');await expect(trigger).toBeVisible();await expect(trigger).toBeFocused();await trigger.click();await page.getByRole('dialog',{name:/할까요/}).locator('button').last().click();await expect(page).toHaveURL(/\/Leave\/Index\?/);expect(f.writes).toHaveLength(1);expect(f.writes[0].sent.get('id')).toBe(id);expect(f.errors).toEqual([]);
});
for(const failure of [403,409,500,'id','employeeId','previousSnapshot','previousStatus','status','navigateTo'])test(`self action refuses unconfirmed acknowledgement ${failure}`,async({page})=>{
  const f=await fixture(page,typeof failure==='number'?{status:failure}:{bad:failure});await send(page,approved);await expect(page.locator(state)).toContainText(failure===403?'저장 권한':failure===409?'충돌':'저장 결과를 확인하지 못했습니다.');await expect(page.locator(row(pending)+' button')).toBeDisabled();expect(f.reads()).toBe(1);expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);
});
test('self actions reattach to actual replaced list and preserve definite invalid retries',async({page})=>{const f=await fixture(page,{status:422});await page.locator('#leaveRequestListForm select[name=RequestLimit]').selectOption('20');await expect.poll(()=>f.reads()).toBe(2);await send(page,pending);await expect(page.locator(state)).toContainText('입력 내용을 확인');await expect(page.locator(row(pending)+' button')).toBeEnabled();await send(page,cancel);await expect.poll(()=>f.writes.length).toBe(2);expect(f.errors).toEqual([]);});
for(const kind of ['scope','dispose','timeout'])test(`self action late response after ${kind} is ignored`,async({page})=>{if(kind==='timeout')await page.clock.install();const f=await fixture(page,{hold:true});await send(page,pending);await expect.poll(()=>f.writes.length).toBe(1);if(kind==='scope')await page.evaluate(()=>document.dispatchEvent(new Event('workspace-entity-scope-change')));else if(kind==='dispose')await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false})));else await page.clock.fastForward(31000);f.release();await expect(page.locator(row(pending)+' button')).toBeDisabled();expect(f.reads()).toBe(1);expect(f.errors).toEqual([]);});
test('a cancellation confirmation freezes its target and cannot submit a modified baseline',async({page})=>{const f=await fixture(page);await page.locator(row(pending)+' button').click();await expect(page.getByRole('dialog',{name:/할까요/})).toBeVisible();await page.locator(row(pending)+' input[name=expectedSnapshot]').evaluate(input=>{input.value='0'.repeat(64);});await page.getByRole('dialog',{name:/할까요/}).locator('button').last().click();await expect(page.getByRole('dialog',{name:/할까요/})).toHaveCount(0);expect(f.writes).toHaveLength(0);await expect(page.locator('#leaveRequestsArea')).toHaveJSProperty('inert',false);expect(f.errors).toEqual([]);});
test('pending cancellation suppresses competing apply, read replacement and warns on exit',async({page})=>{const f=await fixture(page,{hold:true});await page.locator('#openApplyPanel').click();await page.locator('#applyStart').fill(f.model.start);await page.locator('#applyEnd').fill(f.model.start);await page.locator('[name="Input.WorkPlan"]').fill('새 신청 초안');await send(page,pending);await expect.poll(()=>f.writes.length).toBe(1);await page.locator('#applyForm').evaluate(form=>form.requestSubmit());await page.locator('#leaveRequestListForm select[name=RequestLimit]').evaluate(input=>{input.value='20';input.dispatchEvent(new Event('change',{bubbles:true}));});expect(f.writes).toHaveLength(1);expect(f.reads()).toBe(1);expect(await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;})).toBe(true);f.release();await expect(page.locator(state)).toContainText('처리 결과를 확인했습니다.');expect(f.errors).toEqual([]);});
test('pending apply disables cancellation without issuing a second write',async({page})=>{const f=await fixture(page,{hold:true});await page.locator('#openApplyPanel').click();await page.locator('#applyStart').fill(f.model.start);await page.locator('#applyEnd').fill(f.model.start);await page.locator('[name="Input.WorkPlan"]').fill('새 신청');await page.locator('#applyForm button[type=submit]').click();await page.getByRole('dialog',{name:'연차를 신청할까요?'}).getByRole('button',{name:'신청하기',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(1);await expect(page.locator(row(pending)+' button')).toBeDisabled();await page.locator(row(pending)).evaluate(form=>form.requestSubmit());expect(f.writes).toHaveLength(1);f.release();await expect(page.locator('[data-application-state]')).toContainText('저장 결과를 확인하지 못했습니다.');expect(f.errors).toEqual([]);});
test('removed submitting form discards late result and leaves a read-only recovery',async({page})=>{const f=await fixture(page,{hold:true});await send(page,pending);await expect.poll(()=>f.writes.length).toBe(1);await page.locator(row(pending)).evaluate(form=>form.remove());await expect(page.locator(state)).toContainText('화면이 교체되어');f.release();await expect(page.locator(row(approved)+' button')).toBeDisabled();expect(f.reads()).toBe(1);expect(f.errors).toEqual([]);});
