import { describe,it,expect } from 'vitest';
import { Engine } from '../src/server/engine.js';
import { MemoryRepository,hash } from '../src/server/repository.js';
import { ProductSchema,SettingsSchema,type Actor,type Desired,type Job,type Remote,type Row,type Store } from '../src/shared/domain.js';
import { ConnectorError,type Connector } from '../src/server/connectors/types.js';
import { importCatalog,parseSheets } from '../src/server/catalog.js';
import { mergeSteam,steamPrice } from '../src/server/connectors/steam.js';

class Fake implements Connector {
  fingerprint='fake';items=new Map<string,Remote>();writes:string[]=[];failRead=false;loseCreate=false;race=false;loseStep=false;
  constructor(public store:Store){}
  saleCountries=()=>[] as string[];
  async read(id:string){if(this.failRead)throw new ConnectorError('FORBIDDEN','permission','rejected');return structuredClone(this.items.get(id)??null);}
  async validate(_d:Desired){}
  steps(_d:Desired,fields?:string[]){return fields??['prices','activate'];}
  async create(id:string,d:Desired){if(this.race||this.items.has(id))throw new ConnectorError('ALREADY_EXISTS','exists','rejected');this.writes.push('create:'+id);this.items.set(id,{id,data:{name:d.product.name}});if(this.loseCreate)throw new ConnectorError('NETWORK_UNKNOWN','lost');return {id,receipt:{created:true}};}
  async apply(step:string,row:Row){this.writes.push(step+':'+row.remoteId);if(this.loseStep)throw new ConnectorError('NETWORK_UNKNOWN','lost');return {done:true};}
}
const actor:Actor={id:'1',name:'운영자',permissions:['iap.access','iap.publish']};
async function fixture(){const repo=new MemoryRepository();const google=new Fake('google'),apple=new Fake('apple'),steam=new Fake('steam');const connectors={google,apple,steam};const engine=new Engine(repo,(_g,s)=>connectors[s]);
  await repo.put('game','game',{id:'game',name:'게임',connectorKey:'demo'},0);
  const products=['existing','new'].map(key=>ProductSchema.parse({productKey:key,name:key,type:'consumable',googleId:key,appleId:key,steamId:key==='existing'?'1':'2',pricePresetKey:'P5500',localizations:{'ko-KR':{name:'상품',description:'설명'}}}));
  const catalog=await importCatalog(repo,'game',products,'1','test');
  await repo.put('readiness','game',{revision:catalog.snapshotId,keys:products.map(p=>p.productKey)});
  await repo.put('preset','v1',{key:'P5500',name:'5500원',krw:'5500',google:{KR:{currency:'KRW',amount:'5500'}},apple:{KOR:{pricePointId:'reference',currency:'KRW',amount:'5500'}},steam:{KRW:'5500',USD:'3.99'},version:'1',confirmedAt:'2026-09-09T00:00:00Z',confirmedBy:'1'},0);
  for(const c of [google,apple])c.items.set('existing',{id:'existing',data:{state:'inactive',price:'old'}});
  return {repo,engine,google,apple,steam,products};
}
describe('모바일 기존 상품 보호',()=>{
  it.each(['google','apple'] as const)('혼합 업로드·전체 선택·반복 실행: %s 기존 상품 쓰기 0건',async(store)=>{const f=await fixture();const plan=await f.engine.createPlan(actor,{gameId:'game',productKeys:['existing','new','existing'],stores:[store]});await f.engine.enqueue(actor,plan.id,'create');await f.engine.run(plan.id);await f.engine.run(plan.id);expect(f[store].writes).toEqual(['create:new','prices:new','activate:new']);const second=await f.engine.createPlan(actor,{gameId:'game',productKeys:['existing','new'],stores:[store]});await f.engine.enqueue(actor,second.id,'create');await f.engine.run(second.id);expect(f[store].writes).toHaveLength(3);});
  it.each(['inactive','draft','WAITING_FOR_REVIEW','APPROVED'])('%s 상품 보호',async(state)=>{const f=await fixture();f.apple.items.get('existing')!.data.state=state;const p=await f.engine.createPlan(actor,{gameId:'game',productKeys:['existing'],stores:['apple']});expect(p.rows[0].action).toBe('skip');expect(f.apple.writes).toEqual([]);});
  it('조회 실패를 미등록으로 오판하지 않는다',async()=>{const f=await fixture();f.google.failRead=true;await expect(f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['google']})).rejects.toThrow();expect(f.google.writes).toEqual([]);});
  it('Google 앱 판매 국가를 사용하고 저장된 KR 초안은 상품별 제한으로 취급하지 않는다',async()=>{const f=await fixture();f.google.saleCountries=()=>['KR','US'];await f.repo.put('settings','game:new:google',{countries:['KR'],localizations:{},priceOverrides:{},reviewNote:'',submitReview:false,activate:false});const plan=await f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['google']});expect(plan.rows[0].desired.settings.countries).toEqual(['KR','US']);expect(f.google.writes).toEqual([]);});
  it('실행 직전 다른 작업자가 생성하면 건너뛴다',async()=>{const f=await fixture();const p=await f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['google']});await f.engine.enqueue(actor,p.id,'create');f.google.items.set('new',{id:'new',data:{other:true}});const job=await f.engine.run(p.id);expect(job.rows[0].state).toBe('skipped');expect(f.google.writes).toEqual([]);});
  it('조회-생성 사이 충돌을 수정으로 전환하지 않는다',async()=>{const f=await fixture();const p=await f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['google']});await f.engine.enqueue(actor,p.id,'create');f.google.race=true;const j=await f.engine.run(p.id);expect(j.rows[0].state).toBe('skipped');expect(f.google.writes).toEqual([]);});
  it('생성 응답 유실 후 워커 재시작에서 자동 인계하지 않는다',async()=>{const f=await fixture();const p=await f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['apple']});await f.engine.enqueue(actor,p.id,'create');f.apple.loseCreate=true;await f.engine.run(p.id);const restarted=new Engine(f.repo,()=>f.apple);const job=await restarted.run(p.id);expect(job.state).toBe('needs_action');expect(f.apple.writes).toEqual(['create:new']);expect(job.rows[0].created).toBeUndefined();});
  it('생성 요청 도중 프로세스 종료도 미확정으로 멈춘다',async()=>{const f=await fixture();const p=await f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['google']});const j=await f.engine.enqueue(actor,p.id,'create');j.state='running';j.rows[0].state='running';await f.repo.put('job',j.id,j);const result=await f.engine.run(j.id);expect(result.state).toBe('needs_action');expect(f.google.writes).toEqual([]);});
  it('후속 단계 응답 유실 시 해당 단계를 반복하지 않는다',async()=>{const f=await fixture();const p=await f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['apple']});await f.engine.enqueue(actor,p.id,'create');f.apple.loseStep=true;await f.engine.run(p.id);await f.engine.run(p.id);expect(f.apple.writes).toEqual(['create:new','prices:new']);});
  it('프리셋 변경 후 기존 상품은 수정되지 않고 이전 신규 계획은 무효화된다',async()=>{const f=await fixture();const p=await f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['google']});const preset=(await f.repo.list<any>('preset'))[0].data;await f.repo.put('preset','v2',{...preset,krw:'6600',version:'2',confirmedAt:'2026-09-10T00:00:00Z'},0);await expect(f.engine.enqueue(actor,p.id,'create')).rejects.toThrow('변경');const existing=await f.engine.createPlan(actor,{gameId:'game',productKeys:['existing'],stores:['google']});await f.engine.enqueue(actor,existing.id,'create');await f.engine.run(existing.id);expect(f.google.writes).toEqual([]);});
});
describe('일회성 예외 승인',()=>{
  async function change(){const f=await fixture();const p=await f.engine.exceptionPlan(actor,{gameId:'game',productKey:'existing',store:'google',fields:['prices'],reason:'가격표 정정 작업'});return {...f,p};}
  it('승인 없는 실행·일반 경로 우회·권한 없는 요청 차단',async()=>{const f=await change();await expect(f.engine.enqueue(actor,f.p.id,'exception')).rejects.toThrow();await expect(f.engine.enqueue(actor,f.p.id,'create')).rejects.toThrow();await expect(f.engine.approve({...actor,permissions:['iap.access']},f.p.id,'existing')).rejects.toThrow();expect(f.google.writes).toEqual([]);});
  it('ID 직접 입력·승인 사용자 결합',async()=>{const f=await change();await expect(f.engine.approve(actor,f.p.id,'wrong')).rejects.toThrow();await expect(f.engine.approve({...actor,id:'2'},f.p.id,'existing')).rejects.toThrow();});
  it('승인된 필드만 실행하고 승인 재사용 금지',async()=>{const f=await change();const a=await f.engine.approve(actor,f.p.id,'existing');const j=await f.engine.enqueue(actor,f.p.id,'exception',a.id);await f.engine.run(j.id);await f.engine.run(j.id);expect(f.google.writes).toEqual(['prices:existing']);const another=await f.engine.exceptionPlan(actor,{gameId:'game',productKey:'existing',store:'google',fields:['activate'],reason:'판매 상태 변경'});await expect(f.engine.enqueue(actor,another.id,'exception',a.id)).rejects.toThrow();});
  it('10분 만료 및 원격 변경 시 승인 무효',async()=>{const f=await change();const a=await f.engine.approve(actor,f.p.id,'existing');f.engine.now=()=>new Date(Date.now()+601000);await expect(f.engine.enqueue(actor,f.p.id,'exception',a.id)).rejects.toThrow();f.engine.now=()=>new Date();f.google.items.get('existing')!.data.price='changed';await expect(f.engine.enqueue(actor,f.p.id,'exception',a.id)).rejects.toThrow('변경');});
  it('미지원 필드·전체 수정 스위치·상품 ID 변경 거부',async()=>{const f=await fixture();await expect(f.engine.createPlan(actor,{gameId:'game',productKeys:['existing'],stores:['google'],allowUpdates:true})).rejects.toThrow();await expect(f.engine.exceptionPlan(actor,{gameId:'game',productKey:'existing',store:'google',fields:['productId'],reason:'식별자 변경 요청'})).rejects.toThrow();});
});
describe('작업 복구와 불변 계획',()=>{
  it('큐에서 10분 지난 승인은 실행하지 않는다',async()=>{const f=await fixture();const p=await f.engine.exceptionPlan(actor,{gameId:'game',productKey:'existing',store:'google',fields:['prices'],reason:'가격 정정 확인'});const a=await f.engine.approve(actor,p.id,'existing');await f.engine.enqueue(actor,p.id,'exception',a.id);f.engine.now=()=>new Date(Date.now()+601000);expect((await f.engine.run(p.id)).state).toBe('needs_action');expect(f.google.writes).toEqual([]);});
  it('실행 직전 권한 회수는 외부 요청을 막는다',async()=>{const f=await fixture();const p=await f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['google']});await f.engine.enqueue(actor,p.id,'create');const worker=new Engine(f.repo,()=>f.google,()=>new Date(),async()=>{throw new Error('revoked');});await expect(worker.run(p.id)).rejects.toThrow('revoked');expect(f.google.writes).toEqual([]);});
  it('생성 성공 기록 후 재시작은 최초 값과 미완료 단계만 사용한다',async()=>{const f=await fixture();const p=await f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['google']});const j=await f.engine.enqueue(actor,p.id,'create');const result=await f.google.create('new',j.rows[0].desired);j.rows[0].created={...result,at:new Date().toISOString()};j.rows[0].steps[0]={key:'prices',state:'done',receipt:{ok:true}};j.rows[0].state='running';await f.repo.put('job',j.id,j);const next=await new Engine(f.repo,()=>f.google).run(j.id);expect(next.state).toBe('done');expect(f.google.writes).toEqual(['create:new','activate:new']);});
  it('재개 작업의 연결 변경 또는 값 변조를 거부한다',async()=>{const f=await fixture();const p=await f.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['google']});const j=await f.engine.enqueue(actor,p.id,'create');j.rows[0].created={id:'new',at:new Date().toISOString(),receipt:{ok:true}};j.rows[0].state='running';await f.repo.put('job',j.id,j);f.google.fingerprint='different-app';expect((await f.engine.run(j.id)).state).toBe('needs_action');expect(f.google.writes).toEqual([]);const other=await fixture();const op=await other.engine.createPlan(actor,{gameId:'game',productKeys:['new'],stores:['google']});const oj=await other.engine.enqueue(actor,op.id,'create');oj.rows[0].desired.preset.krw='1';await other.repo.put('job',oj.id,oj);await expect(other.engine.run(oj.id)).rejects.toThrow('최초');expect(other.google.writes).toEqual([]);});
  it('같은 상품을 위한 두 작업은 하나만 생성한다',async()=>{const f=await fixture();const input={gameId:'game',productKeys:['new'],stores:['google']};const a=await f.engine.createPlan(actor,input),b=await f.engine.createPlan(actor,input);await f.engine.enqueue(actor,a.id,'create');await f.engine.enqueue(actor,b.id,'create');await Promise.all([f.engine.run(a.id),f.engine.run(b.id)]);f.engine.now=()=>new Date(Date.now()+600000);await f.engine.run(b.id);expect(f.google.writes.filter(v=>v.startsWith('create:'))).toEqual(['create:new']);});
});

describe('시트와 Steam',()=>{
  it('JSON의 빈 구매 이력 키를 시트의 빈 셀로 가져올 수 있고 실제 키 삭제는 거부한다',async()=>{const f=await fixture();await importCatalog(f.repo,'game',f.products.map(p=>({...p,saveName:''})),'1','json');const result=await importCatalog(f.repo,'game',f.products,'1','sheet');expect(result.products.every(p=>p.saveName==='')).toBe(true);await expect(importCatalog(f.repo,'game',f.products.map(p=>({...p,saveName:'changed'})),'1','json')).rejects.toThrow('saveName');const g=await fixture();await importCatalog(g.repo,'game',g.products.map(p=>({...p,saveName:'permanent-history'})),'1','json');await expect(importCatalog(g.repo,'game',g.products,'1','sheet')).rejects.toThrow('saveName');});
  it('중복 ID·번역·키를 거부한다',()=>{expect(()=>parseSheets([['productKey','name','type','pricePresetKey'],['a','A','consumable','P'],['a','A','consumable','P']],[['productKey','locale','name','description']])).toThrow();});
  it('누락 상품을 삭제하지 않고 ID 변경을 거부한다',async()=>{const f=await fixture();const result=await importCatalog(f.repo,'game',[f.products[0]],'1','sheet');expect(result.products).toHaveLength(2);expect(result.missingKeys).toEqual(['new']);await expect(importCatalog(f.repo,'game',[{...f.products[0],googleId:'other'}],'1','sheet')).rejects.toThrow();});
  it('선택한 Steam 항목만 병합하고 알 수 없는 필드 보존',async()=>{const f=await fixture();const source=await f.engine.source('game');const desired=await f.engine.desired(source,'new','steam');const old={custom:'keep',products:[{itemId:'1',amount:10,unrecognized:{x:1}},{itemId:'2',amount:1,custom:true}]};const result=JSON.parse(mergeSteam(JSON.stringify(old),[{id:'2',desired}]));expect(result.products[0]).toEqual(old.products[0]);expect(result.products[1].custom).toBe(true);expect(result.products[1].prices.USD).toBe(399);expect(result.custom).toBe('keep');});
  it('통화 단위를 검증한다',()=>{expect(steamPrice('5500','KRW')).toBe(5500);expect(steamPrice('3.99','USD')).toBe(399);expect(steamPrice('500','JPY')).toBe(50000);expect(()=>steamPrice('5501','KRW')).toThrow();expect(()=>steamPrice('1.001','USD')).toThrow();});
  it('Steam 기존 게임 식별자와 구매 이력 키를 Google ID로 바꾸지 않는다',async()=>{const f=await fixture();const desired=await f.engine.desired(await f.engine.source('game'),'new','steam');desired.product.googleId='google_override';desired.product.saveName='sheet_value';const result=JSON.parse(mergeSteam(JSON.stringify({products:[{itemId:'2',productId:'game_identity',saveName:'existing_history'}]}),[{id:'2',desired}]));expect(result.products[0].productId).toBe('game_identity');expect(result.products[0].saveName).toBe('existing_history');});
});
