import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, cpSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { spawnSync } from 'node:child_process';
import { root, outputs } from '../build-ui.mjs';
import { collectThemeSources } from '../check-theme-contract.mjs';
import { checkPrimitives } from '../check-ui-primitives.mjs';

test('generator registers a real page, server route and shared UI; refuses duplicate/unsupported requests',()=>{
  mkdirSync(resolve(root,'artifacts'),{recursive:true});
  const temporary=mkdtempSync(resolve(root,'artifacts/generator-'));
  function copy(file){ const destination=resolve(temporary,file); mkdirSync(dirname(destination),{recursive:true});cpSync(resolve(root,file),destination,{recursive:true}); }
  for(const file of ['packages','tooling/build-ui.mjs','tooling/check-architecture.mjs','tooling/check-native-post-boundaries.mjs','tooling/check-network-boundaries.mjs','tooling/check-owned-modals.mjs','tooling/check-schedule-task-writes.mjs','tooling/check-theme-contract.mjs','tooling/check-ui-primitives.mjs','tooling/create-page.mjs'])copy(file);
  const networkPolicy=JSON.parse(readFileSync(resolve(root,'packages/contracts/network-boundaries.json'),'utf8'));
  for(const entry of networkPolicy.entries)copy(entry.path);
  const postPolicy=JSON.parse(readFileSync(resolve(root,'packages/contracts/native-post-boundaries.json'),'utf8'));
  for(const entry of postPolicy.entries)copy(entry.path);
  for(const file of collectThemeSources(root,JSON.parse(readFileSync(resolve(root,'packages/contracts/services.json'),'utf8'))))copy(file);
  const original=JSON.parse(readFileSync(resolve(root,'packages/contracts/pages.json'),'utf8'));
  for(const page of original.pages)copy(page.entry);
  copy('apps/sheet/src/client');
  copy('apps/sheet/src/server/index.ts');
  copy('apps/schedule/src');
  copy('apps/schedule/index.html');
  copy('apps/schedule/server/TaskRoutes.cs');
  copy('apps/schedule/server/TaskWriteProtocol.cs');
  copy('apps/schedule/server/ImageRoutes.cs');
  copy('apps/schedule/server/ImageWriteProtocol.cs');
  copy('apps/schedule/server/DiscussionRoutes.cs');
  copy('apps/schedule/server/CommentWriteProtocol.cs');
  copy('apps/schedule/server/ManagementRoutes.cs');
  copy('apps/schedule/server/MilestoneWriteProtocol.cs');
  copy('apps/schedule/server/ReleaseRoutes.cs');
  copy('apps/schedule/server/ReleaseWriteProtocol.cs');
  copy('apps/schedule/server/PersonalTodoRoutes.cs');
  copy('apps/schedule/server/PersonalTodoWriteProtocol.cs');
  copy('apps/portal/Pages');
  copy('apps/portal/Program.cs');
  copy('apps/portal/wwwroot/js/account-create.js');
  copy('apps/cs/public/player-data.js');
  copy('apps/cs/public/player-data.css');
  copy('apps/cs/public/playfab-logs.js');
  copy('apps/cs/public/playfab-logs.css');
  copy('apps/cs/public/app.js');
  copy('apps/cs/public/steam-refunds.css');
  copy('apps/cs/public/product-commands.js');
  copy('apps/cs/public/product-commands.css');
  copy('apps/statistics/app-server.js');
  copy('apps/leave/Pages');
  copy('apps/leave/Program.cs');
  copy('apps/leave/Services/LeaveRequestService.cs');
  copy('apps/leave/Services/LeaveRequestSnapshot.cs');
  copy('apps/leave/Services/LeaveSettlementService.cs');
  copy('apps/leave/Services/LeaveGrantSnapshot.cs');
  copy('apps/leave/Services/LeaveSettlementSnapshot.cs');
  copy('apps/leave/scripts/preview-mobile.mjs');
  copy('apps/leave/wwwroot/js/notification-center.js');
  copy('apps/leave/wwwroot/js/audit-logs.js');
  copy('apps/leave/wwwroot/js/discord-settings.js');
  copy('apps/leave/wwwroot/css/site.css');
  copy('apps/leave/wwwroot/css/approval-forms.css');
  const run=(...args)=>spawnSync(process.execPath,args,{cwd:temporary,encoding:'utf8'});
  const created=run('tooling/create-page.mjs','cs','quality-review','검증 페이지');
  assert.equal(created.status,0,created.stderr);
  const registered=JSON.parse(readFileSync(resolve(temporary,'packages/contracts/pages.json'),'utf8')).pages.find(p=>p.path==='/quality-review');
  assert.equal(registered.permission,'cs.access');
  assert.match(readFileSync(resolve(temporary,registered.entry),'utf8'),/data-workspace-navigation="cs"/);
  assert.ok(readFileSync(resolve(temporary,'apps/cs/lib/workspace-pages.js'),'utf8').includes('/quality-review'));
  const spaEntry=resolve(temporary,'apps/statistics/public/index.html');
  const before=readFileSync(spaEntry,'utf8');
  const spa=run('tooling/create-page.mjs','statistics','quality-review','통계 <검증>');
  assert.equal(spa.status,0,spa.stderr);
  const after=readFileSync(spaEntry,'utf8');
  assert.match(after,/data-page="qualityReview"/);
  assert.match(after,/통계 &lt;검증&gt;/);
  const unstamp=s=>s.replace(/company-workspace\.(js|css)\?v=[\w.]+/g,'company-workspace.$1?v=VERSION');
  assert.equal(unstamp(after.replace(/  <section class="page hidden" data-page="qualityReview">.*<\/section>\n/,'')),unstamp(before),'Existing SPA body must remain unchanged');
  const routes=readFileSync(resolve(temporary,'apps/statistics/public/workspace-routes.js'),'utf8');
  assert.ok(routes.includes('/quality-review'));
  assert.ok(routes.includes('qualityReview'));
  const sheetApp=readFileSync(resolve(temporary,'apps/sheet/src/client/App.tsx'),'utf8');
  const react=run('tooling/create-page.mjs','sheet','quality-review','시트 검증');
  assert.equal(react.status,0,react.stderr);
  assert.match(readFileSync(resolve(temporary,'apps/sheet/src/client/pages/quality-review.tsx'),'utf8'),/export default function Page/);
  assert.match(readFileSync(resolve(temporary,'apps/sheet/src/client/generated/workspace-pages.tsx'),'utf8'),/qualityReview.*<Page0\/>/);
  assert.equal(readFileSync(resolve(temporary,'apps/sheet/src/client/App.tsx'),'utf8'),sheetApp,'React generator must not rewrite existing app state or business logic');
  assert.ok(readFileSync(resolve(temporary,'apps/sheet/src/shared/workspace-routes.ts'),'utf8').includes('/quality-review'));
  const scheduleApp=readFileSync(resolve(temporary,'apps/schedule/src/App.tsx'),'utf8');
  const schedule=run('tooling/create-page.mjs','schedule','quality-review','일정 검증');
  assert.equal(schedule.status,0,schedule.stderr);
  assert.match(readFileSync(resolve(temporary,'apps/schedule/src/pages/quality-review.tsx'),'utf8'),/export default function Page/);
  assert.match(readFileSync(resolve(temporary,'apps/schedule/src/generated/workspace-pages.tsx'),'utf8'),/qualityReview.*<Page0\/>/);
  assert.equal(readFileSync(resolve(temporary,'apps/schedule/src/App.tsx'),'utf8'),scheduleApp,'Schedule generation must preserve board, task and dialog logic');
  assert.ok(readFileSync(resolve(temporary,'apps/schedule/server/WorkspaceRoutes.g.cs'),'utf8').includes('/quality-review'));
  const portalLayout=readFileSync(resolve(temporary,'apps/portal/Pages/Shared/_Layout.cshtml'),'utf8');
  const portal=run('tooling/create-page.mjs','home','quality-review','회사 검증');
  assert.equal(portal.status,0,portal.stderr);
  const portalPage=readFileSync(resolve(temporary,'apps/portal/Pages/Workspace/quality-review.cshtml'),'utf8');
  assert.match(portalPage,/@page\s/);assert.match(portalPage,/@workspacePage.Title/);
  assert.equal(readFileSync(resolve(temporary,'apps/portal/Pages/Shared/_Layout.cshtml'),'utf8'),portalLayout);
  const serverPages=readFileSync(resolve(temporary,'apps/portal/Workspace/WorkspacePageDefinitions.g.cs'),'utf8');
  assert.match(serverPages,/"home.quality.review".*"EmployeeOnly", false, true/);
  const leave=run('tooling/create-page.mjs','leave','quality-review','연차 검증');
  assert.equal(leave.status,0,leave.stderr);
  assert.match(readFileSync(resolve(temporary,'apps/leave/Workspace/WorkspacePageDefinitions.g.cs'),'utf8'),/"leave.quality.review".*"EmployeeOnly", false, true/);
  for(const command of [['tooling/build-ui.mjs','--check'],['tooling/check-architecture.mjs']]){
    const checked=run(...command);assert.equal(checked.status,0,checked.stderr);
  }
  assert.ok(outputs(temporary).get('apps/cs/lib/workspace-pages.js').includes('/quality-review'),'explicit base must read fixture catalog, not the host workspace');
  assert.equal(checkPrimitives(temporary).remaining,JSON.parse(readFileSync(resolve(temporary,'packages/contracts/ui-primitive-debt.json'),'utf8')).entries.reduce((sum,row)=>sum+row.count,0));
  const newStyle=resolve(temporary,'apps/cs/public/quality-review.css');
  writeFileSync(newStyle,'.quality-review { background:var(--cw-nonexistent); }');
  const rejectedTheme=run('tooling/check-architecture.mjs');
  assert.notEqual(rejectedTheme.status,0);assert.match(rejectedTheme.stderr,/quality-review.css.*undefined/);
  writeFileSync(newStyle,'.quality-review { background:var(--cw-raised); }');
  assert.equal(run('tooling/check-architecture.mjs').status,0);
  // Generated pages must not become a loophole for new body UI. Stamped HTML is
  // editable source, not an exempt generated asset. Also reject additions inside
  // an existing legacy file; its debt entries are not a whole-file allowance.
  const newPage=resolve(temporary,registered.entry),originalPage=readFileSync(newPage,'utf8');
  for(const file of [newPage,spaEntry,resolve(temporary,'apps/schedule/src/Settings.tsx')]){
    const source=readFileSync(file,'utf8');
    writeFileSync(file,source+'\n<button>New raw action</button>');
    const rejected=run('tooling/check-architecture.mjs');
    assert.notEqual(rejected.status,0);assert.match(rejected.stderr,/native-button: new\/increased/);
    writeFileSync(file,source);
  }
  writeFileSync(newPage,originalPage+'\n<input class="cw-form-control"><button class="cw-button">Action</button>');
  assert.equal(run('tooling/check-architecture.mjs').status,0);
  writeFileSync(newPage,originalPage);
  const custom=resolve(temporary,'apps/schedule/src/generated/custom.tsx');
  writeFileSync(custom,'export const custom = <button>Not generated</button>;');
  const rejectedCustom=run('tooling/check-architecture.mjs');
  assert.notEqual(rejectedCustom.status,0);assert.match(rejectedCustom.stderr,/generated\/custom.tsx.*native-button/);
  const debtFile=resolve(temporary,'packages/contracts/ui-primitive-debt.json'),debtBefore=readFileSync(debtFile,'utf8');
  const pruneNew=run('tooling/check-ui-primitives.mjs','--prune');
  assert.notEqual(pruneNew.status,0);assert.equal(readFileSync(debtFile,'utf8'),debtBefore,'prune cannot accept a new violation when the reviewed debt is empty');
  writeFileSync(custom,'export const custom = <button className="cw-button">Shared</button>;');
  assert.equal(JSON.parse(debtBefore).sealed,true);assert.equal(JSON.parse(debtBefore).entries.length,0);
  const unsealed=JSON.parse(debtBefore);unsealed.sealed=false;writeFileSync(debtFile,JSON.stringify(unsealed));
  const rejectedSeal=run('tooling/check-architecture.mjs');assert.notEqual(rejectedSeal.status,0);assert.match(rejectedSeal.stderr,/seal must remain enabled/);
  const restored=JSON.parse(debtBefore);restored.files=[{path:'apps/demo/Page.cshtml',reason:'restore',removeWhen:'later'}];restored.entries=[{path:'apps/demo/Page.cshtml',rule:'native-button',signature:'a'.repeat(64),count:1}];writeFileSync(debtFile,JSON.stringify(restored));
  const rejectedAllowance=run('tooling/check-architecture.mjs');assert.notEqual(rejectedAllowance.status,0);assert.match(rejectedAllowance.stderr,/allowances cannot be restored/);
  writeFileSync(debtFile,debtBefore);
  assert.equal(run('tooling/check-architecture.mjs').status,0);
  const generatedAdapter=resolve(temporary,'apps/schedule/src/generated/workspace-state.tsx'),adapterBefore=readFileSync(generatedAdapter,'utf8');
  writeFileSync(generatedAdapter,adapterBefore+'\nexport const raw = <button/>;');
  const tampered=run('tooling/check-ui-primitives.mjs');
  assert.notEqual(tampered.status,0);assert.match(tampered.stderr,/Generated UI changed outside its shared owner/);
  writeFileSync(generatedAdapter,adapterBefore);
  writeFileSync(resolve(temporary,'apps/schedule/src/example.test.tsx'),'const testFixture = <button/>;');
  assert.equal(run('tooling/check-architecture.mjs').status,0,'conventional test fixtures are not app UI');
  const duplicate=run('tooling/create-page.mjs','cs','quality-review','중복');assert.notEqual(duplicate.status,0);
  const duplicateSpa=run('tooling/create-page.mjs','statistics','quality-review','중복');assert.notEqual(duplicateSpa.status,0);
  const duplicateReact=run('tooling/create-page.mjs','sheet','quality-review','중복');assert.notEqual(duplicateReact.status,0);
  const duplicateSchedule=run('tooling/create-page.mjs','schedule','quality-review','중복');assert.notEqual(duplicateSchedule.status,0);
  const duplicateRazor=run('tooling/create-page.mjs','home','quality-review','중복');assert.notEqual(duplicateRazor.status,0);
  const reserved=run('tooling/create-page.mjs','statistics','api','금지');assert.notEqual(reserved.status,0);
  const malformed=run('tooling/create-page.mjs','statistics','quality--review','잘못된 이름');assert.notEqual(malformed.status,0);
  assert.equal(unstamp(readFileSync(spaEntry,'utf8')),unstamp(after),'Rejected generation must not mutate SPA body');
  const unsupported=run('tooling/create-page.mjs','unknown','quality-review','미등록');assert.notEqual(unsupported.status,0);
  const registry=JSON.parse(readFileSync(resolve(temporary,'packages/contracts/pages.json'),'utf8'));
  assert.equal(registry.pages.length,original.pages.length+6);
  for(const page of registry.pages.filter(p=>p.path==='/quality-review')){
    const source=readFileSync(resolve(temporary,page.entry),'utf8');
    if(page.entry.endsWith('.tsx')){
      assert.match(source,/import \{ WorkspaceState \} from '\.\.\/generated\/workspace-state'/);
      assert.match(source,/<WorkspaceState kind="empty"/);
      assert.match(readFileSync(resolve(dirname(resolve(temporary,page.entry)),'../generated/workspace-state.tsx'),'utf8'),/CompanyState/);
    }else assert.match(source,/data-workspace-state="empty"/);
  }
});
