/* GENERATED by tooling/build-ui.mjs. Edit packages/workspace-ui or packages/contracts, not this file. */
export const PAGE_PATHS: readonly string[] = ["/","/index.html","/projects/:gameId/products/new","/projects/:gameId/products/import","/projects/:gameId/products/:productKey","/plans/:planId","/presets","/jobs","/projects"];
