/* GENERATED by tooling/build-ui.mjs. Edit packages/workspace-ui or packages/contracts, not this file. */
namespace CompanyPortal.Workspace;
public class AccountInput
{
    public string AccountType { get; set; } = "employee";
    public bool IsActive { get; set; } = true;
    public string Name { get; set; } = "";
    public string Email { get; set; } = "";
    public long? DepartmentId { get; set; }
    public DateOnly? HireDate { get; set; }
    public string BirthDate { get; set; } = "";
    public long[] ProjectIds { get; set; } = [];
    public bool IsPrivate { get; set; }
    public string Role { get; set; } = "employee";
    public string[] Permissions { get; set; } = [];
}
public sealed record AccountField(string Key, string Label, string Section, string Placement, int? MaxLength);
public static class AccountFields
{
    public static readonly AccountField[] All = [
        new("AccountType", "계정 유형", "identity", "summary", null),
        new("IsActive", "계정 상태", "identity", "summary", null),
        new("Name", "이름", "identity", "detail", 100),
        new("Email", "Google 이메일", "identity", "detail", 200),
        new("DepartmentId", "부서", "identity", "detail", null),
        new("HireDate", "입사일", "identity", "detail", null),
        new("BirthDate", "생일", "identity", "detail", 5),
        new("ProjectIds", "참여 프로젝트", "identity", "detail", null),
        new("IsPrivate", "비공개 직원", "identity", "detail", null),
        new("Role", "회사 역할", "access", "summary", null),
        new("Permissions", "추가 시스템 접근", "access", "permissions", null)
    ];
}
