/* GENERATED by tooling/build-ui.mjs. Edit packages/workspace-ui or packages/contracts, not this file. */
namespace CompanyPortal.Workspace;
public static partial class WorkspacePages
{
    public static readonly WorkspacePage[] All = [
        new("home.dashboard", "/Index", "/", ["/Index"], "업무 도구", null, true, true, new Dictionary<string, string> {}),
        new("home.profile", "/Settings/Profile", "/settings/profile", [], "개인 설정", "EmployeeOnly", false, true, new Dictionary<string, string> {}),
        new("home.users", "/Admin/Users", "/Admin/Users", [], "계정·접근 권한", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("home.departments", "/Admin/Organization", "/Admin/Organization", [], "부서 관리", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("home.projects", "/Admin/Organization", "/Admin/Organization", [], "프로젝트 관리", "AdminOnly", false, true, new Dictionary<string, string> {["tab"] = "projects"}),
        new("home.notifications", "/Notifications/Index", "/notifications", [], "통합 알림센터", "EmployeeOnly", false, false, new Dictionary<string, string> {}),
        new("home.denied", "/Account/AccessDenied", "/Account/AccessDenied", [], "접근할 수 없음", null, true, false, new Dictionary<string, string> {}),
        new("home.error", "/Error", "/Error", [], "오류", null, true, false, new Dictionary<string, string> {})
    ];
}
