/* GENERATED by tooling/build-ui.mjs. Edit packages/workspace-ui or packages/contracts, not this file. */
namespace Schedule;
public static class WorkspaceRoutes
{
    public static readonly string[] Patterns = ["/", "/index.html", "/comparison", "/mine", "/todos", "/releases", "/settings", "/kanban", "/feedback", "/feedback/{id:long:min(1)}", "/tasks/{id:long:min(1)}"];
}
