/* GENERATED by tooling/build-ui.mjs. Edit packages/workspace-ui or packages/contracts, not this file. */
export const PAGE_PATHS: readonly string[] = ["/overview","/","/index.html","/migration","/translations","/releases","/snapshots"];
