/* GENERATED by tooling/build-ui.mjs. Edit packages/workspace-ui or packages/contracts, not this file. */
namespace LeaveManager.Workspace;
public static partial class WorkspacePages
{
    public static readonly WorkspacePage[] All = [
        new("leave.dashboard", "/Leave/Index", "/Leave", ["/Leave/Index"], "내 연차", "EmployeeOnly", false, true, new Dictionary<string, string> {}),
        new("leave.usage", "/Leave/Usage", "/Leave/Usage", [], "사용 통계", "EmployeeOnly", false, true, new Dictionary<string, string> {}),
        new("leave.discord", "/Settings/Discord", "/Settings/Discord", [], "Discord 알림 설정", "EmployeeOnly", false, true, new Dictionary<string, string> {}),
        new("leave.approvals", "/Admin/Index", "/Admin", ["/Admin/Index"], "신청 승인 관리", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("leave.employees", "/Admin/Employees", "/Admin/Employees", [], "회사 직원 연결 현황", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("leave.employee.usage", "/Admin/Usage", "/Admin/Usage", [], "직원 사용 통계", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("leave.adjustments", "/Admin/Adjustments", "/Admin/Adjustments", [], "직원 연차 추가·삭제", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("leave.holidays", "/Admin/Holidays", "/Admin/Holidays", [], "공휴일 관리", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("leave.settlements", "/Admin/Settlements", "/Admin/Settlements", [], "소멸·이월·보상", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("leave.audit", "/Admin/AuditLogs", "/Admin/AuditLogs", [], "감사 로그", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("leave.notifications.settings", "/Admin/NotificationSettings", "/Admin/NotificationSettings", [], "디스코드 채널 알림", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("leave.security", "/Admin/Security", "/Admin/Security", [], "보안 점검", "AdminOnly", false, true, new Dictionary<string, string> {}),
        new("leave.notifications", "/Notifications/Index", "/Notifications", ["/Notifications/Index"], "알림", "EmployeeOnly", false, false, new Dictionary<string, string> {}),
        new("leave.master.employees", "/Master/Employees", "/Master/Employees", [], "회사 계정 연결 현황", "MasterOnly", false, false, new Dictionary<string, string> {}),
        new("leave.denied", "/Account/AccessDenied", "/Account/AccessDenied", [], "접근 권한 없음", null, true, false, new Dictionary<string, string> {})
    ];
}
