import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
export const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = path => readFileSync(resolve(root,path),'utf8').replaceAll('\r\n','\n');
export function* walk(directory,base=root) {
  for (const item of readdirSync(resolve(base,directory), {withFileTypes:true})) {
    if (['node_modules','bin','obj','.git','dist','data','wwwroot'].includes(item.name)) continue;
    const path = directory+'/'+item.name;
    if (item.isDirectory()) yield* walk(path,base); else yield path;
  }
}
export function validateAccountFields(fields) {
  const keys = new Set();
  for (const field of fields) {
    if (!/^[A-Z][A-Za-z0-9]*$/.test(field.key) || keys.has(field.key)) throw Error('Invalid/duplicate account field key');
    keys.add(field.key);
    if (!['string','bool','long?','DateOnly?','long[]','string[]'].includes(field.type) || !field.label?.trim()) throw Error('Invalid account field type/label');
    if (!['identity','access'].includes(field.section) || !['summary','detail','permissions'].includes(field.placement)) throw Error('Invalid account field layout');
    if (field.maxLength !== undefined && (!Number.isSafeInteger(field.maxLength) || field.maxLength < 1)) throw Error('Invalid account field length');
    if (field.default !== undefined && !((field.type === 'string' && typeof field.default === 'string') || (field.type === 'bool' && typeof field.default === 'boolean'))) throw Error('Invalid account field default');
  }
}
export function outputs(base=root) {
  const read=path=>readFileSync(resolve(base,path),'utf8').replaceAll('\r\n','\n');
  const companyLogo=readFileSync(resolve(base,'packages/workspace-ui/assets/company-logo.png'));
  const catalog = { ...JSON.parse(read('packages/contracts/services.json')), ...JSON.parse(read('packages/contracts/pages.json')) };
  const banner = '/* GENERATED by tooling/build-ui.mjs. Edit packages/workspace-ui or packages/contracts, not this file. */\n';
  const accountFields = JSON.parse(read('packages/contracts/account-fields.json')).fields;
  const mobile = JSON.parse(read('packages/contracts/mobile-app.json'));
  validateAccountFields(accountFields);
  let js = banner + 'window.CompanyPageCatalog = '+JSON.stringify(catalog).replaceAll('<','\\u003c')+';\n'+read('packages/workspace-ui/src/entity-display.js')+'\n'+read('packages/workspace-ui/src/entity-choices.js')+'\n'+read('packages/workspace-ui/src/states.js')+'\n'+read('packages/workspace-ui/src/read-session.js')+'\n'+read('packages/workspace-ui/src/navigation.js');
  js = banner + read('packages/workspace-ui/src/notification-contract.js') + '\n' + read('packages/workspace-ui/src/notification-session.js') + '\n' + read('packages/workspace-ui/src/context-contract.js') + '\n' + js.slice(banner.length);
  js = js + '\n' + read('packages/workspace-ui/src/forms.js');
  js = js + '\n' + read('packages/workspace-ui/src/clipboard.js');
  js = js + '\n' + read('packages/workspace-ui/src/dialogs.js');
  js = js + '\n' + read('packages/workspace-ui/src/review.js');
  js = js + '\n' + read('packages/workspace-ui/src/disclosure.js');
  js = js + '\n' + read('packages/workspace-ui/src/image-editor.js');
  js = js + '\n' + read('packages/workspace-ui/src/profile.js');
  js = js + '\n' + read('packages/workspace-ui/src/project-icon.js');
  js = js + '\n' + read('packages/workspace-ui/src/company-workspace.js');
  js = js + '\n' + read('packages/workspace-ui/src/page-router.js');
  const css = banner+read('packages/workspace-ui/src/company-workspace.css')+'\n'+read('packages/workspace-ui/src/navigation.css')+'\n'+read('packages/workspace-ui/src/primitives.css');
  const entities = banner+read('packages/workspace-ui/src/company-entities.js');
  const version=createHash('sha256').update(js).update(css).update(entities).update(companyLogo).digest('hex').slice(0,16);
  js=js.replace(/company-entities\.js\?v=[\w.]+/g, 'company-entities.js?v='+version);
  // Published compatibility paths also support external consumers such as IAP.
  const result = new Map([
    ['apps/portal/wwwroot/js/company-workspace.js',js],
    ['apps/portal/wwwroot/css/company-workspace.css',css],
    ['apps/portal/wwwroot/js/company-entities.js',entities],
    ['apps/portal/wwwroot/images/company-logo.png',companyLogo]
  ]);
  const assetLinks=JSON.stringify([{
    relation:['delegate_permission/common.handle_all_urls','delegate_permission/common.use_as_origin'],
    target:{namespace:'android_app',package_name:mobile.packageId,sha256_cert_fingerprints:[mobile.signingCertificateSha256]}
  }],null,2)+'\n';
  const assetLinkRoots=[
    'apps/portal/wwwroot','apps/leave/wwwroot','apps/schedule/public','apps/cs/public',
    'apps/statistics/public','apps/sheet/src/client/public','apps/iap/public'
  ];
  for(const target of assetLinkRoots) result.set(target+'/.well-known/assetlinks.json',assetLinks);
  result.set('apps/portal/wwwroot/manifest.webmanifest',JSON.stringify({
    name:mobile.appName,short_name:mobile.appName,start_url:'/',scope:'/',display:'standalone',
    background_color:'#101114',theme_color:'#101114',
    icons:[{src:'/images/company-logo.png',sizes:'512x512',type:'image/png',purpose:'any maskable'}]
  },null,2)+'\n');
  const androidValues=`<?xml version="1.0" encoding="utf-8"?>\n<resources>\n  <string name="app_name">${mobile.appName}</string>\n  <string name="package_id">${mobile.packageId}</string>\n  <string name="start_url">${mobile.startUrl}</string>\n  <string name="trusted_origins">${mobile.trustedOrigins.join(',')}</string>\n</resources>\n`;
  result.set('apps/mobile-android/app/src/main/res/values/mobile_contract.xml',androidValues);
  result.set('apps/mobile-android/app/src/main/res/drawable/company_logo.png',companyLogo);
  const accountProperties = accountFields.map(f => `    public ${f.type} ${f.key} { get; set; }${f.default !== undefined ? ' = '+JSON.stringify(f.default)+';' : f.type.endsWith('[]') ? ' = [];' : ''}`).join('\n');
  result.set('apps/portal/Workspace/AccountFields.g.cs', banner + `namespace CompanyPortal.Workspace;\npublic class AccountInput\n{\n${accountProperties}\n}\npublic sealed record AccountField(string Key, string Label, string Section, string Placement, int? MaxLength);\npublic static class AccountFields\n{\n    public static readonly AccountField[] All = [\n${accountFields.map(f => '        new('+[f.key,f.label,f.section,f.placement,f.maxLength??null].map(x=>JSON.stringify(x)).join(', ')+')').join(',\n')}\n    ];\n}\n`);
  result.set('packages/workspace-ui/assets-manifest.json',JSON.stringify({version,files:[...result].map(([path,body])=>({path,sha256:createHash('sha256').update(body).digest('hex')}))},null,2)+'\n');
  // Stamp all existing adapters from the same content hash. No manual version fan-out.
  for (const file of walk('apps',base)) {
    if (!/\.(?:cshtml|html)$/.test(file)) continue;
    const before=read(file);
    if (!/company-workspace\.(?:js|css)\?v=/.test(before)) continue;
    result.set(file,before.replace(/(company-workspace\.(?:js|css)\?v=)[\w.]+/g, '$1'+version));
  }
  // Generated route allowlist is consumed by CS behind its existing auth gateway.
  const csRoutes=catalog.pages.filter(p=>p.service==='cs').flatMap(p=>[p.path,...(p.aliases||[])].map(path=>[path,[p.entry.replace('apps/cs/public/',''),'text/html; charset=utf-8']]));
  result.set('apps/cs/lib/workspace-pages.js',banner+'export default '+JSON.stringify(csRoutes,null,2)+';\n');
  for(const service of catalog.services.filter(s=>s.adapter==='static-spa')) {
    const pages=catalog.pages.filter(p=>p.service===service.id);
    const routes=Object.fromEntries(pages.map(p=>[p.view,{path:p.path,title:p.title,aliases:p.aliases||[]}]));
    const pageFiles=pages.flatMap(p=>[p.path,...p.aliases||[]].map(path=>[path,[p.entry.replace(`apps/${service.app}/public/`,''),'text/html; charset=utf-8']]));
    result.set(`apps/${service.app}/public/workspace-routes.js`,banner+'export const ROUTES = '+JSON.stringify(routes,null,2)+';\nexport const PAGE_FILES = '+JSON.stringify(pageFiles,null,2)+';\n');
  }
  for(const service of catalog.services.filter(s=>s.adapter==='react'&&s.navigation==='shared')) {
    const pages=catalog.pages.filter(p=>p.service===service.id);
    const base=`apps/${service.app}/${service.client}`;
    const additional=pages.filter(p=>p.entry!==base+'/App.tsx');
    result.set(base+'/generated/workspace-navigation.tsx',banner+read('packages/workspace-ui/react/workspace-navigation.tsx'));
    result.set(base+'/generated/workspace-state.tsx',banner+read('packages/workspace-ui/react/workspace-state.tsx'));
    result.set(base+'/generated/workspace-read.ts',banner+read('packages/workspace-ui/react/workspace-read.ts'));
    result.set(base+'/generated/workspace-form.ts',banner+read('packages/workspace-ui/react/workspace-form.ts'));
    result.set(base+'/generated/workspace-modal.ts',banner+read('packages/workspace-ui/react/workspace-modal.ts'));
    result.set(base+'/generated/workspace-disclosure.ts',banner+read('packages/workspace-ui/react/workspace-disclosure.ts'));
    result.set(base+'/generated/workspace-review.ts',banner+read('packages/workspace-ui/react/workspace-review.ts'));
    result.set(base+'/generated/workspace-confirm.ts',banner+read('packages/workspace-ui/react/workspace-confirm.ts'));
    result.set(base+'/generated/workspace-entity.tsx',banner+read('packages/workspace-ui/react/workspace-entity.tsx'));
    result.set(base+'/generated/workspace-suggestions.tsx',banner+read('packages/workspace-ui/react/workspace-suggestions.tsx'));
    const imports=additional.map((p,i)=>`import Page${i} from '../${p.entry.slice(base.length+1).replace(/\.tsx$/,'')}';`).join('\n');
    result.set(base+'/generated/workspace-pages.tsx',banner+imports+'\nexport const PAGES = '+JSON.stringify(pages,null,2)+' as const;\nexport type View = typeof PAGES[number]["view"];\nexport const additionalPages = {'+additional.map((p,i)=>`${JSON.stringify(p.view)}:<Page${i}/>`).join(',')+'};\n');
    const routes=pages.flatMap(p=>[p.path,...p.aliases||[]]);
    if(service.serverAdapter==='aspnet')result.set(`apps/${service.app}/server/WorkspaceRoutes.g.cs`,banner+'namespace Schedule;\npublic static class WorkspaceRoutes\n{\n    public static readonly string[] Patterns = ['+routes.map(p=>JSON.stringify(p.replace(':id','{id:long:min(1)}'))).join(', ')+'];\n}\n');
    else result.set(`apps/${service.app}/src/shared/workspace-routes.ts`,banner+'export const PAGE_PATHS: readonly string[] = '+JSON.stringify(routes)+';\n');
  }
  for(const service of catalog.services.filter(s=>s.adapter==='razor'&&s.navigation==='shared')) {
    const pages=catalog.pages.filter(p=>p.service===service.id);
    const literal=value=>JSON.stringify(value);
    const array=items=>'['+items.map(literal).join(', ')+']';
    const rows=pages.map(p=>'        new('+[p.id,p.entry.slice(`apps/${service.app}/Pages`.length).replace(/\.cshtml$/,''),p.path].map(literal).join(', ')+', '+array(p.aliases||[])+', '+literal(p.title)+', '+literal(p.policy||null)+', '+Boolean(p.anonymous)+', '+(p.nav!==false)+', new Dictionary<string, string> {'+Object.entries(p.query||{}).map(([key,value])=>`[${literal(key)}] = ${literal(value)}`).join(', ')+'})');
    result.set(`apps/${service.app}/Workspace/WorkspacePages.g.cs`,banner+read('packages/workspace-ui/razor/WorkspacePages.cs').replaceAll('__WORKSPACE_NAMESPACE__',service.namespace));
    result.set(`apps/${service.app}/Workspace/WorkspacePageDefinitions.g.cs`,banner+`namespace ${service.namespace};\npublic static partial class WorkspacePages\n{\n    public static readonly WorkspacePage[] All = [\n${rows.join(',\n')}\n    ];\n}\n`);
  }
  return result;
}
export function build(check = false) {
  for (const [file,body] of outputs()) {
    const path=resolve(root,file);
    if (check) {
      const matches=existsSync(path)&&(Buffer.isBuffer(body)?readFileSync(path).equals(body):read(file)===body);
      if (!matches) throw Error(`Generated asset differs: ${file}. Run npm run build:ui; never edit outputs directly.`);
    } else { mkdirSync(dirname(path),{recursive:true}); writeFileSync(path,body); }
  }
}
if (process.argv[1] && resolve(process.argv[1])===fileURLToPath(import.meta.url)) { build(process.argv.includes('--check')); console.log('Shared UI assets verified/generated.'); }
